//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_Process
    {
        public int Record_ID { get; set; }
        public string Session_ID { get; set; }
        public int Inv_Reference { get; set; }
        public string Extract_Type { get; set; }
        public Nullable<bool> Processed { get; set; }
    }
}
