
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class BatchTrace
{

    public int BatchTrace_Reference { get; set; }

    public int Batch_Reference { get; set; }

    public Nullable<int> MWithdrawal_Reference { get; set; }

    public Nullable<int> PWithdrawal_Reference { get; set; }

    public Nullable<int> STrace_Reference { get; set; }

    public Nullable<int> TTrace_Reference { get; set; }

    public Nullable<int> ManPart_Batch_Reference { get; set; }

    public Nullable<int> WOComp_Batch_Reference { get; set; }

    public bool Included { get; set; }

}

}
