
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class BuildBOMView
{

    public int BuildBom_Reference { get; set; }

    public int Build_Reference { get; set; }

    public int IsDefaultBuild { get; set; }

    public int Parent_Part_Reference { get; set; }

    public string Parent_Part_Number { get; set; }

    public string Parent_Part_Issue { get; set; }

    public string Parent_Name { get; set; }

    public string Parent_Specification { get; set; }

    public string Component_Type { get; set; }

    public Nullable<int> Part_Reference { get; set; }

    public Nullable<int> Material_Reference { get; set; }

    public decimal Qty_Per { get; set; }

    public string Notes { get; set; }

    public string Part_Number { get; set; }

    public string Part_Issue { get; set; }

    public string Name { get; set; }

    public string Specification { get; set; }

    public Nullable<int> Default_Build_Reference { get; set; }

}

}
