//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildBom
    {
        public int BuildBOM_Reference { get; set; }
        public int Build_Reference { get; set; }
        public int Parent_Part_Reference { get; set; }
        public string Component_Type { get; set; }
        public Nullable<int> Part_Reference { get; set; }
        public Nullable<int> Material_Reference { get; set; }
        public decimal Qty_Per { get; set; }
        public string Notes { get; set; }
    }
}
