//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationEquipment
    {
        public int Calibration_Equipment_Ref { get; set; }
        public string Equipment_Prefix { get; set; }
        public Nullable<int> Equipment_Number { get; set; }
        public string Equipment_Suffix { get; set; }
        public Nullable<int> Calibration_Procedure_Ref { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> Date_Purchased { get; set; }
        public Nullable<System.DateTime> Date_First_Active { get; set; }
        public string Calibration_Period { get; set; }
        public Nullable<int> Calibration_Interval { get; set; }
        public string Check_Period { get; set; }
        public Nullable<int> Check_Interval { get; set; }
        public string Colour_Code { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string Notes2 { get; set; }
        public Nullable<System.DateTime> Date_Last_Calibration { get; set; }
        public Nullable<System.DateTime> Date_Next_Calibration { get; set; }
        public Nullable<System.DateTime> Date_Last_Check { get; set; }
        public Nullable<System.DateTime> Date_Next_Check { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<System.DateTime> Date_Last_Active { get; set; }
        public Nullable<double> Uses_Before_Calibration { get; set; }
        public Nullable<double> Uses_Before_Check { get; set; }
        public Nullable<double> Used_Since_Calibration { get; set; }
        public Nullable<double> Used_Since_Check { get; set; }
        public Nullable<double> Notifier_Offset_Cal { get; set; }
        public Nullable<double> Activity_Date_Offset_Cal { get; set; }
        public Nullable<double> Notifier_Offset_Chk { get; set; }
        public Nullable<double> Activity_Date_Offset_Chk { get; set; }
        public string SerialNumber { get; set; }
        public string UDFF01 { get; set; }
        public string UDFF02 { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public string UDF07 { get; set; }
        public string UDF08 { get; set; }
        public Nullable<System.DateTime> UDFD01 { get; set; }
        public Nullable<System.DateTime> UDFD02 { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public Nullable<int> Created_By { get; set; }
        public string Category { get; set; }
        public Nullable<int> Procedure_Reference { get; set; }
        public byte[] Notes { get; set; }
    }
}
