
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Concession_View
{

    public int Concession_Reference { get; set; }

    public string Concession_Prefix { get; set; }

    public Nullable<int> Concession_Number { get; set; }

    public string Concession_Suffix { get; set; }

    public string Description { get; set; }

    public string FullRef { get; set; }

}

}
