//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_Calendar
    {
        public int CP_Calendar_Reference { get; set; }
        public int WCentre_Reference { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ISO_Week { get; set; }
        public Nullable<int> ISO_WeekYear { get; set; }
        public Nullable<System.DateTime> Start_DateTime { get; set; }
        public Nullable<System.DateTime> End_DateTime { get; set; }
        public Nullable<int> AvailableS { get; set; }
    }
}
