
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Quotes
{

    public int Quote_Reference { get; set; }

    public string User_Reference { get; set; }

    public Nullable<int> Sequence { get; set; }

    public string Group_Reference { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> Prepared { get; set; }

    public Nullable<int> Year_Prepared { get; set; }

    public Nullable<int> Month_Prepared { get; set; }

    public Nullable<System.DateTime> FollowUpDate { get; set; }

    public decimal Price { get; set; }

    public double Quote_Qty { get; set; }

    public double Planned_Qty { get; set; }

    public bool Main { get; set; }

    public Nullable<System.DateTime> Delivery_Date { get; set; }

    public Nullable<System.DateTime> Date_Created { get; set; }

    public Nullable<int> Part_Reference { get; set; }

    public string Part_Number { get; set; }

    public string Part_Issue { get; set; }

    public string Drawing_Number { get; set; }

    public string Drawing_Issue { get; set; }

    public string DrawingNoAndIssue { get; set; }

    public string PartNoAndIssue { get; set; }

    public Nullable<decimal> Part_Total_Cost { get; set; }

    public Nullable<decimal> Material_Total_Cost { get; set; }

    public Nullable<decimal> SubContract_Total_Cost { get; set; }

    public Nullable<decimal> Tool_Total_Cost { get; set; }

    public Nullable<decimal> WCentre_Total_Cost { get; set; }

    public decimal Total_Cost { get; set; }

    public Nullable<int> Customer_Reference { get; set; }

    public string Customer { get; set; }

    public Nullable<int> Contact_Reference { get; set; }

    public string Title_Full_Name { get; set; }

    public string Customer_Enquiry_Number { get; set; }

    public Nullable<double> Quote_Value { get; set; }

    public Nullable<int> Owned_By { get; set; }

    public string Owned_By_Name { get; set; }

    public Nullable<System.DateTime> EnquiryDate { get; set; }

    public Nullable<System.DateTime> IssuedDate { get; set; }

    public Nullable<System.DateTime> AcceptedDate { get; set; }

    public Nullable<int> EnqToPrepDays { get; set; }

    public Nullable<int> EnqToIssuedDays { get; set; }

    public Nullable<int> EnqToAcceptedDays { get; set; }

    public Nullable<int> IssuedToAcceptedDays { get; set; }

    public string Status { get; set; }

    public string Summary_Status { get; set; }

}

}
