
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Customers
{

    public int Customer_Reference { get; set; }

    public string External_Customer { get; set; }

    public string Name { get; set; }

    public bool On_Stop { get; set; }

    public bool Approved { get; set; }

    public string Owner { get; set; }

    public Nullable<int> PlanningColour { get; set; }

    public int Is_Stock_Customer { get; set; }

    public string Main_Customer_Address { get; set; }

    public string Full_Main_Customer_Address { get; set; }

    public string Main_Customer_Post_Code { get; set; }

    public string Customer_Telephone { get; set; }

    public string Customer_Email { get; set; }

    public string Main_Contact_Full_Name { get; set; }

    public string Main_Contact_Telephone { get; set; }

    public string Main_Contact_Email { get; set; }

}

}
