
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_OTIF
{

    public string Customer { get; set; }

    public Nullable<int> WOrder_Reference { get; set; }

    public string WO_User_Reference { get; set; }

    public Nullable<System.DateTime> Batch_Delivery_Date { get; set; }

    public string Delivery_MonthYear { get; set; }

    public string Delivery_YearMonth { get; set; }

    public System.DateTime Delivery_Date { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<int> No_of_Batches { get; set; }

    public Nullable<int> OTIF { get; set; }

}

}
