
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class DashboardPage
{

    public int ID { get; set; }

    public string UserName { get; set; }

    public int Page { get; set; }

    public string PageName { get; set; }

    public Nullable<int> Sequence { get; set; }

    public Nullable<bool> AutoPage { get; set; }

    public Nullable<int> IntervalS { get; set; }

    public Nullable<bool> Shared { get; set; }

}

}
