
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Suppliers
{

    public int Supplier_Reference { get; set; }

    public string Name { get; set; }

    public string Main_Supplier_Address { get; set; }

    public string Full_Main_Supplier_Address { get; set; }

    public string Main_Supplier_Post_Code { get; set; }

    public string Supplier_Telephone { get; set; }

    public string Supplier_Email { get; set; }

    public string Main_Contact_Full_Name { get; set; }

    public string Main_Contact_Telephone { get; set; }

    public string Main_Contact_Email { get; set; }

    public string Rating { get; set; }

}

}
