//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardItem
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserGroup { get; set; }
        public string WidgetName { get; set; }
        public string WidgetCategory { get; set; }
        public string LibraryType { get; set; }
        public Nullable<int> Page { get; set; }
        public string TileType { get; set; }
        public string TileCaption { get; set; }
        public Nullable<int> TilesX { get; set; }
        public Nullable<int> TilesY { get; set; }
        public Nullable<int> TilesWide { get; set; }
        public Nullable<int> TilesHigh { get; set; }
        public string WidgetDefXML { get; set; }
        public System.DateTime DateModified { get; set; }
        public string WidgetGUID { get; set; }
        public string Base64Picture { get; set; }
        public string AboutSummary { get; set; }
        public string AboutDetails { get; set; }
        public Nullable<int> MinScriptNumber { get; set; }
        public Nullable<decimal> WidgetVersion { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
