
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Contacts
{

    public int Contact_Reference { get; set; }

    public string Surname { get; set; }

    public string Forename { get; set; }

    public string Title { get; set; }

    public string Position { get; set; }

    public string Full_Name { get; set; }

    public string Title_Full_Name { get; set; }

    public string Contact_Telephone { get; set; }

    public string Contact_Email { get; set; }

    public Nullable<int> Customer_Reference { get; set; }

    public Nullable<int> Supplier_Reference { get; set; }

}

}
