
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_POFirstLastPromiseDates
{

    public int PItem_Reference { get; set; }

    public Nullable<System.DateTime> First_Promise_Date { get; set; }

    public Nullable<System.DateTime> Last_Promise_Date { get; set; }

}

}
