
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Batches
{

    public int Batch_Reference { get; set; }

    public string Batch_User_Reference { get; set; }

    public Nullable<System.DateTime> Delivery_Date { get; set; }

    public Nullable<System.DateTime> Delivery_Date_Null_WO_Date { get; set; }

    public System.DateTime Delivery_Date_Null_Today { get; set; }

    public int No_Del_Date { get; set; }

    public System.DateTime Delivery_Date_Overdue_Today { get; set; }

    public Nullable<System.DateTime> Workshop_Date { get; set; }

    public double Batch_Qty { get; set; }

    public bool Delivery_Required { get; set; }

    public Nullable<int> DItem_Reference { get; set; }

    public bool Invoice_Required { get; set; }

    public Nullable<int> InvItem_Reference { get; set; }

    public Nullable<bool> Proforma_Required { get; set; }

    public Nullable<int> ProItem_Reference { get; set; }

    public decimal Batch_Sales_Value { get; set; }

    public bool Scrapped { get; set; }

    public bool Hold { get; set; }

    public bool Added_To_Stock { get; set; }

    public bool Went_To_Quarantine { get; set; }

    public bool ForStock { get; set; }

    public Nullable<int> Delivery_Month { get; set; }

    public Nullable<int> Delivery_Year { get; set; }

    public string Delivery_YearMonth { get; set; }

    public string Delivery_MonthYear { get; set; }

    public Nullable<int> OverDays { get; set; }

    public Nullable<int> OverMonths { get; set; }

    public string Delivery_MonthYearOD { get; set; }

    public string Delivery_WeekYearOD { get; set; }

    public Nullable<int> Reserve_WOPart_Reference { get; set; }

    public Nullable<int> Reserve_WOrder_Reference { get; set; }

    public Nullable<int> Rebuilding_Batch_Reference { get; set; }

    public Nullable<int> WOrder_Reference { get; set; }

    public string WO_User_Reference { get; set; }

    public Nullable<int> WO_Sequence { get; set; }

    public string UserRefAndSeq { get; set; }

    public string PartNoAndIssue { get; set; }

    public string DrawingNoAndIssue { get; set; }

    public string Description { get; set; }

    public string Customer { get; set; }

    public string Customer_Owner { get; set; }

    public Nullable<int> Customer_Reference { get; set; }

    public Nullable<int> Is_Stock_Customer { get; set; }

    public Nullable<int> PlanningColour { get; set; }

    public string Customer_Order_Number { get; set; }

    public string Customer_Order_Item { get; set; }

    public Nullable<double> SO_Qty { get; set; }

    public Nullable<double> Full_Order_Sales_Value { get; set; }

    public string WO_Status { get; set; }

    public Nullable<System.DateTime> WO_Prepared { get; set; }

    public Nullable<int> WO_Year_Prepared { get; set; }

    public Nullable<int> WO_Month_Prepared { get; set; }

    public int Invoiced { get; set; }

    public int Delivered { get; set; }

    public int Reserved { get; set; }

    public string Batch_Status { get; set; }

    public string Type_Of_Order { get; set; }

    public string Location { get; set; }

    public string Order_Type_Code { get; set; }

}

}
