
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Materials
{

    public int Material_Reference { get; set; }

    public string Description { get; set; }

    public string Specification { get; set; }

    public string Form { get; set; }

    public string UOM { get; set; }

    public string Part_Number { get; set; }

    public string Part_Issue { get; set; }

    public string PartNoAndIssue { get; set; }

    public string DrawingNoAndIssue { get; set; }

    public Nullable<int> Supplier_Reference { get; set; }

    public string Supplier { get; set; }

    public double Existing_Stock { get; set; }

    public double Existing_Quarantine { get; set; }

    public double Replenish_Level { get; set; }

    public double Minimum_Stock { get; set; }

    public decimal Cost { get; set; }

    public int Cost_Quantity { get; set; }

    public Nullable<double> Stock_Value { get; set; }

    public string Stock_Category { get; set; }

    public bool Active_Record { get; set; }

    public Nullable<int> Created_By { get; set; }

    public string Created_By_Name { get; set; }

    public Nullable<int> Owned_By { get; set; }

    public string Owned_By_Name { get; set; }

}

}
