
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Deliveries
{

    public int DNote_Reference { get; set; }

    public string DNote_User_Reference { get; set; }

    public System.DateTime Delivery_Date { get; set; }

    public Nullable<System.DateTime> Despatch_Date { get; set; }

    public Nullable<int> Delivery_Year { get; set; }

    public Nullable<int> Delivery_Month { get; set; }

    public string Delivery_MonthYear { get; set; }

    public string Delivery_YearMonth { get; set; }

    public Nullable<int> DItem_Reference { get; set; }

    public Nullable<double> Quantity { get; set; }

    public string Delivery_Status { get; set; }

    public Nullable<int> Batch_Reference { get; set; }

    public string Batch_User_Reference { get; set; }

    public Nullable<decimal> Batch_Sales_Value { get; set; }

    public Nullable<int> WOrder_Reference { get; set; }

    public string WO_User_Reference { get; set; }

    public Nullable<int> WO_Sequence { get; set; }

    public Nullable<int> Customer_Reference { get; set; }

    public string Customer { get; set; }

    public Nullable<int> Is_Stock_Customer { get; set; }

    public Nullable<System.DateTime> Batch_Delivery_Date { get; set; }

}

}
