
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_RFQs
{

    public int RFQ_Reference { get; set; }

    public string User_Reference { get; set; }

    public Nullable<System.DateTime> Date_Created { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> Expires { get; set; }

    public Nullable<int> Created_By { get; set; }

    public string Created_By_Name { get; set; }

    public Nullable<int> Owned_By { get; set; }

    public string Owned_By_Name { get; set; }

    public Nullable<int> Item_Count { get; set; }

    public Nullable<int> Supplier_Count { get; set; }

    public Nullable<int> Responses_Count { get; set; }

    public Nullable<int> Excluded_Count { get; set; }

    public Nullable<int> Expected_Responses_Count { get; set; }

    public Nullable<int> OS_Responses_Count { get; set; }

    public int RFQ_Open { get; set; }

}

}
