
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_PO_Items
{

    public decimal View_Version { get; set; }

    public int PItem_Reference { get; set; }

    public int POrder_Reference { get; set; }

    public string User_Reference { get; set; }

    public string Supplier { get; set; }

    public Nullable<int> Supplier_Reference { get; set; }

    public Nullable<System.DateTime> Order_Date { get; set; }

    public Nullable<int> Order_Year { get; set; }

    public Nullable<int> Order_Month { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public string Specification { get; set; }

    public double Quantity { get; set; }

    public double Quantity_Delivered { get; set; }

    public Nullable<double> OS_Qty { get; set; }

    public Nullable<double> OS_Cost { get; set; }

    public Nullable<decimal> Unit_Cost { get; set; }

    public decimal Item_Total_Cost { get; set; }

    public Nullable<decimal> Item_Minimum_Cost { get; set; }

    public Nullable<System.DateTime> Required_Date { get; set; }

    public Nullable<System.DateTime> Required_Date_Or_Now { get; set; }

    public Nullable<System.DateTime> Promise_Date { get; set; }

    public Nullable<System.DateTime> First_Promise_Date { get; set; }

    public Nullable<System.DateTime> Last_Promise_Date { get; set; }

    public Nullable<System.DateTime> Delivery_Date { get; set; }

    public Nullable<int> Promise_Days_Late { get; set; }

    public Nullable<int> Required_Days_Late { get; set; }

    public string Promise_Status { get; set; }

    public string Required_Status { get; set; }

    public Nullable<System.DateTime> Calc_Expected_Date { get; set; }

    public Nullable<int> Calc_Expected_Year { get; set; }

    public Nullable<int> Calc_Expected_Month { get; set; }

    public string Calc_Expected_MonthYear { get; set; }

    public string Calc_Delivery_MonthYear { get; set; }

    public string Calc_Required_MonthYearOD { get; set; }

    public Nullable<int> WOrder_Reference { get; set; }

    public string Status { get; set; }

}

}
