
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Dash_Op_Employees_Count
{

    public int WOWCentre_Reference { get; set; }

    public Nullable<int> Employee_Count { get; set; }

    public Nullable<int> Single_Employee_Reference { get; set; }

}

}
