
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class DashRanx
{

    public int ID { get; set; }

    public string RangeName { get; set; }

    public int Range01From { get; set; }

    public Nullable<int> Range01To { get; set; }

    public Nullable<int> Range01Colour { get; set; }

    public Nullable<int> Range02To { get; set; }

    public Nullable<int> Range02Colour { get; set; }

    public Nullable<int> Range03To { get; set; }

    public Nullable<int> Range03Colour { get; set; }

    public Nullable<int> Range04To { get; set; }

    public Nullable<int> Range04Colour { get; set; }

    public Nullable<int> Range05To { get; set; }

    public Nullable<int> Range05Colour { get; set; }

    public Nullable<int> Range01FontColour { get; set; }

    public Nullable<int> Range02FontColour { get; set; }

    public Nullable<int> Range03FontColour { get; set; }

    public Nullable<int> Range04FontColour { get; set; }

    public Nullable<int> Range05FontColour { get; set; }

}

}
