//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLinkCategory
    {
        public int ID { get; set; }
        public string DataType { get; set; }
        public string CategoryDesc { get; set; }
        public Nullable<bool> Jobpack { get; set; }
    }
}
