
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class DocumentLink
{

    public int ID { get; set; }

    public string DataType { get; set; }

    public int DataReference { get; set; }

    public Nullable<int> Category { get; set; }

    public string Path { get; set; }

    public Nullable<int> AttachedBy { get; set; }

    public Nullable<System.DateTime> AttachedOn { get; set; }

    public string Note { get; set; }

}

}
