//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_Reference { get; set; }
        public string Name { get; set; }
        public string Job_Description { get; set; }
        public string Clock_Number { get; set; }
        public Nullable<bool> EmployeeIsActive { get; set; }
        public Nullable<int> Old_Reference { get; set; }
        public string Pin { get; set; }
        public string Email_Account_User_Name { get; set; }
        public string Email_Address { get; set; }
        public string Email_Password { get; set; }
        public string Email_Signature { get; set; }
        public string Email_Font_Name { get; set; }
        public Nullable<int> Email_Font_Size { get; set; }
        public Nullable<bool> Email_Dialog_Modal { get; set; }
        public Nullable<bool> Email_BCC_Myself { get; set; }
    }
}
