//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class EU_Material_MRP
    {
        public Nullable<decimal> To_Be_Sourced { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<decimal> stock_left { get; set; }
        public Nullable<decimal> PO_Incomming { get; set; }
        public Nullable<decimal> To_order { get; set; }
        public string status { get; set; }
        public int Supplier_reference { get; set; }
        public Nullable<decimal> PO_For_Stock { get; set; }
        public Nullable<decimal> PO_For_Worder { get; set; }
        public string description { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> supplier_ref_wo { get; set; }
        public Nullable<int> sort_no { get; set; }
        public Nullable<System.DateTime> Schedule_date { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Material_Reference { get; set; }
        public Nullable<int> womaterial_reference { get; set; }
        public string Expr1 { get; set; }
    }
}
