
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class EU_Title_Mrp
{

    public Nullable<int> Material_Reference { get; set; }

    public Nullable<decimal> To_Be_Sourced { get; set; }

    public Nullable<decimal> stock { get; set; }

    public string Material_Name { get; set; }

    public Nullable<decimal> Stock_Left { get; set; }

    public Nullable<decimal> PO_Incomming { get; set; }

    public Nullable<decimal> To_order { get; set; }

    public Nullable<decimal> PO_For_Stock { get; set; }

    public Nullable<decimal> PO_For_Worder { get; set; }

    public string Supplier_Name { get; set; }

}

}
