
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class EU_WIP
{

    public string User_Reference { get; set; }

    public int WOrder_Reference { get; set; }

    public Nullable<double> Est_Mat { get; set; }

    public Nullable<double> Act_Mat { get; set; }

    public Nullable<double> Est_Op { get; set; }

    public Nullable<double> Act_Op { get; set; }

    public Nullable<double> Act_Ops_From_Estimates { get; set; }

    public Nullable<double> Act_Ops_Complete_From_Estimates { get; set; }

    public Nullable<double> Est_Part { get; set; }

    public Nullable<double> Act_Part { get; set; }

    public Nullable<double> Est_SubCon { get; set; }

    public Nullable<double> Act_SubCon { get; set; }

    public Nullable<double> Est_Tool { get; set; }

    public Nullable<double> Act_tool { get; set; }

    public Nullable<double> Outstanding_Batches { get; set; }

    public Nullable<double> Total_Batches { get; set; }

    public Nullable<double> Percent_left { get; set; }

    public double percentage_comp { get; set; }

}

}
