//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fave
    {
        public int Fave_Reference { get; set; }
        public string Item_Type { get; set; }
        public int Item_Reference { get; set; }
        public int Employee_Reference { get; set; }
        public string Comment { get; set; }
    }
}
