//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialHeader
    {
        public string Recipient { get; set; }
        public string InterfaceType { get; set; }
        public Nullable<bool> Detail { get; set; }
        public string DeliveryWords { get; set; }
        public string Notes { get; set; }
        public string OutputLocation { get; set; }
        public Nullable<System.DateTime> LastDateUsed { get; set; }
        public bool IssuedOnly { get; set; }
        public Nullable<bool> MultiCurrency { get; set; }
    }
}
