//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Images_Reference { get; set; }
        public string DataType { get; set; }
        public string DataReference { get; set; }
        public string DataImageType { get; set; }
        public string PictureFormat { get; set; }
        public byte[] Picture { get; set; }
        public string Note { get; set; }
    }
}
