
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class InterfaceType
{

    public string Recipient { get; set; }

    public bool Invoices { get; set; }

    public bool Purchases { get; set; }

    public bool Optional_Detail { get; set; }

}

}
