//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_ADDINFO
    {
        public string PK { get; set; }
        public string FK { get; set; }
        public decimal SEQNUM { get; set; }
        public decimal MODE { get; set; }
        public decimal TYPE { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public string VALUE2 { get; set; }
        public string FORMAT { get; set; }
        public string MATCHCODE { get; set; }
        public string SCRIPT { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> ISDISABLED { get; set; }
        public Nullable<decimal> COLOR { get; set; }
        public Nullable<decimal> GHOSTSHIFT { get; set; }
        public Nullable<decimal> CAPDOM1 { get; set; }
        public Nullable<decimal> CAPDOM2 { get; set; }
        public Nullable<decimal> CAPDOM3 { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
