
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class JD_BOXDATA
{

    public string BOXID { get; set; }

    public string OPERATIONID { get; set; }

    public string BOXOPID { get; set; }

    public Nullable<decimal> BOXPPARTS { get; set; }

    public Nullable<decimal> BOXAPARTS { get; set; }

    public Nullable<decimal> BOXATE { get; set; }

    public string CNAME { get; set; }

    public Nullable<System.DateTime> CDATE { get; set; }

    public string CHNAME { get; set; }

    public Nullable<System.DateTime> CHDATE { get; set; }

}

}
