
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class JD_BOM
{

    public string PK { get; set; }

    public string FK { get; set; }

    public string TLFK { get; set; }

    public string TYPEFK { get; set; }

    public string PATH { get; set; }

    public decimal LEVEL { get; set; }

    public decimal SEQNUM { get; set; }

    public decimal NODETYPE { get; set; }

    public decimal PPARTS { get; set; }

    public string OPNAME { get; set; }

    public string CNAME { get; set; }

    public Nullable<System.DateTime> CDATE { get; set; }

    public string CHNAME { get; set; }

    public Nullable<System.DateTime> CHDATE { get; set; }

}

}
