//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_EXCHANGE_PLAN
    {
        public string PK { get; set; }
        public string SYNCPLAN { get; set; }
        public Nullable<decimal> READONLY { get; set; }
        public Nullable<decimal> INTERVAL { get; set; }
        public string BITMAP { get; set; }
        public Nullable<System.DateTime> LASTSYNC { get; set; }
        public string SQLSCRIPT { get; set; }
        public string SCRIPTTEXT { get; set; }
        public string SCRIPTTYP { get; set; }
        public string DBNAME { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
