//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_EAI_LOGBOOK
    {
        public string ID { get; set; }
        public string FNID { get; set; }
        public string WFCOMMENT { get; set; }
        public string INFORMATION { get; set; }
        public string FNINPUT { get; set; }
        public string FNOUTPUT { get; set; }
        public string FNRETURN { get; set; }
        public string ERRORCODE { get; set; }
        public string ERRORDESCR { get; set; }
        public string VERSION { get; set; }
        public string WORKFLOW { get; set; }
        public string WFEID { get; set; }
        public string HOST { get; set; }
        public Nullable<decimal> ISERROR { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public string SESSIONID { get; set; }
        public byte[] TS { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
