//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_LIC_CONNECTION
    {
        public string USERID { get; set; }
        public Nullable<decimal> USERTYPE { get; set; }
        public Nullable<decimal> PROCESSID { get; set; }
        public string HOSTID { get; set; }
        public string LOGINID { get; set; }
        public string ARTICLELIST { get; set; }
        public Nullable<decimal> SUICIDE { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
    }
}
