//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_MR_FRAGSHARE
    {
        public string PKID { get; set; }
        public string ID { get; set; }
        public string WORKERID { get; set; }
        public string FRAGMENTID { get; set; }
        public Nullable<decimal> MRFSTYPE { get; set; }
        public Nullable<decimal> MRTYPE { get; set; }
        public Nullable<decimal> CREATIONMODE { get; set; }
        public Nullable<decimal> BOFFSET { get; set; }
        public Nullable<decimal> PDURATION { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
