
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class JD_MDC_LAYOUTS
{

    public string PK { get; set; }

    public string NAME { get; set; }

    public string DESCR { get; set; }

    public string PRESETID { get; set; }

    public string TABTEXT1 { get; set; }

    public string TABTEXT2 { get; set; }

    public string TABTEXT3 { get; set; }

    public string TABTEXT4 { get; set; }

    public Nullable<decimal> TABVISIBLE1 { get; set; }

    public Nullable<decimal> TABVISIBLE2 { get; set; }

    public Nullable<decimal> TABVISIBLE3 { get; set; }

    public Nullable<decimal> TABVISIBLE4 { get; set; }

    public Nullable<decimal> TOUCHMODE { get; set; }

    public Nullable<decimal> DONOTSHOWFUNCTIONSELECTION { get; set; }

    public string SCRIPT_LOAD { get; set; }

    public string CNAME { get; set; }

    public Nullable<System.DateTime> CDATE { get; set; }

    public string CHNAME { get; set; }

    public Nullable<System.DateTime> CHDATE { get; set; }

}

}
