//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_MESDUMP
    {
        public string PK { get; set; }
        public decimal TYPE { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public byte[] DATAMEMO { get; set; }
        public Nullable<System.DateTime> SCHEDULEFROM { get; set; }
        public Nullable<System.DateTime> SCHEDULETO { get; set; }
        public Nullable<decimal> COUNTSINGLEPARTS { get; set; }
        public Nullable<decimal> COUNTFRAGMENTS { get; set; }
        public Nullable<decimal> COUNT1 { get; set; }
        public Nullable<decimal> COUNT2 { get; set; }
        public Nullable<decimal> COUNT3 { get; set; }
        public Nullable<decimal> COUNT4 { get; set; }
        public Nullable<decimal> COUNT5 { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> BLOBCOMPLETE { get; set; }
    }
}
