
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class JD_MDC_LAYOUTDATA
{

    public string PK { get; set; }

    public string LFK { get; set; }

    public string LAYER { get; set; }

    public string ELEMENTID { get; set; }

    public string PROPERTYID { get; set; }

    public string ALTERNATECAPTION { get; set; }

    public string PRESETSTRING { get; set; }

    public string VIEWFORMAT { get; set; }

    public string BARCODEKEY { get; set; }

    public Nullable<decimal> USEBARCODE { get; set; }

    public Nullable<decimal> ISVISIBLE { get; set; }

    public Nullable<decimal> ISENABLED { get; set; }

    public Nullable<decimal> ALLOWVISIBLEWF { get; set; }

    public Nullable<decimal> ALLOWENABLEWF { get; set; }

    public Nullable<decimal> DONOTALLOWNOINPUT { get; set; }

    public Nullable<decimal> VALIDATELOSTFOCUS { get; set; }

    public Nullable<decimal> SHOWVALIDATERESULT { get; set; }

    public string PROPERTYVALUE { get; set; }

    public string PROPERTYMEMO { get; set; }

    public Nullable<decimal> ELEMENTPOSITION { get; set; }

    public Nullable<decimal> AUTOMATIC { get; set; }

    public string CNAME { get; set; }

    public Nullable<System.DateTime> CDATE { get; set; }

    public string CHNAME { get; set; }

    public Nullable<System.DateTime> CHDATE { get; set; }

}

}
