//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_PALLET_BASE
    {
        public string PKID { get; set; }
        public string CELLREF { get; set; }
        public string DESCR { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> PALCOLOR { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
