//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_REPORTS
    {
        public string PK { get; set; }
        public string FK { get; set; }
        public Nullable<decimal> RTYPE { get; set; }
        public string FULLPATH { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> DUPLICATES { get; set; }
        public string PRINTERNAME { get; set; }
        public Nullable<decimal> PRINTERTRAY { get; set; }
        public string TAKEOVER { get; set; }
        public string VBSCRIPT { get; set; }
        public Nullable<decimal> COMPANYLOGO { get; set; }
        public Nullable<decimal> SPECIAL { get; set; }
        public Nullable<decimal> CANUPDATE { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
