
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class JD_TESTEQPRESET
{

    public decimal OPNO { get; set; }

    public decimal SNNO { get; set; }

    public Nullable<decimal> CALCMODE { get; set; }

    public Nullable<decimal> CALCVALUE { get; set; }

    public string CNAME { get; set; }

    public Nullable<System.DateTime> CDATE { get; set; }

    public string CHNAME { get; set; }

    public Nullable<System.DateTime> CHDATE { get; set; }

}

}
