//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JD_TESTEQUIPMENT
    {
        public decimal FKNO { get; set; }
        public Nullable<decimal> CURRENTCOUNTER { get; set; }
        public Nullable<decimal> MAXCOUNTER { get; set; }
        public Nullable<decimal> CALIBRATIONCOUNTER { get; set; }
        public Nullable<System.DateTime> CALIBRATIONDATE { get; set; }
        public Nullable<decimal> ISLOCKED { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
