
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class KPI_OperatorProductivity
{

    public Nullable<System.DateTime> Date { get; set; }

    public string Type { get; set; }

    public Nullable<double> Time { get; set; }

    public string name { get; set; }

}

}
