//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi_GanntData
    {
        public Nullable<System.DateTime> recStartDate { get; set; }
        public string Name { get; set; }
        public string STARTED { get; set; }
        public string ENDED { get; set; }
        public Nullable<int> Employee_Reference { get; set; }
        public string startDate { get; set; }
        public string enddate { get; set; }
        public string Job { get; set; }
        public string WOrder1 { get; set; }
        public string Job_Description { get; set; }
        public string Clock_Number { get; set; }
        public string Centre_Id { get; set; }
        public string Shiftstart { get; set; }
        public Nullable<System.DateTime> Recorded_Start_Date { get; set; }
        public int Expr1 { get; set; }
        public Nullable<System.DateTime> Date_Of_Activity { get; set; }
        public int WOTimes_Reference { get; set; }
        public Nullable<int> Time { get; set; }
    }
}
