
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class KPI_OPERATORTIMES
{

    public Nullable<System.DateTime> STARTS { get; set; }

    public Nullable<System.DateTime> ENDS { get; set; }

    public int WOTimes_Reference { get; set; }

}

}
