//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi_GanntView
    {
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Stop { get; set; }
        public string Job { get; set; }
        public string JobDetails { get; set; }
        public string Name { get; set; }
        public int EmpRef { get; set; }
        public int WOTimes_Reference { get; set; }
    }
}
