//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSearchView
    {
        public string Name { get; set; }
        public string Specification { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int Cost_Quantity { get; set; }
        public Nullable<double> Existing_Stock { get; set; }
        public Nullable<decimal> Minimum_Charge { get; set; }
        public string Form { get; set; }
        public Nullable<double> Length { get; set; }
        public string Location { get; set; }
        public string Drawing_Number { get; set; }
        public string Drawing_Issue { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Uplift_Percentage { get; set; }
        public Nullable<double> Size { get; set; }
        public string Unit_Of_Measurement { get; set; }
        public string Thickness_Diameter { get; set; }
        public string Part_Number { get; set; }
        public string Part_Issue { get; set; }
        public int Material_Reference { get; set; }
        public Nullable<int> Supplier_Reference { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<double> Maximum_Stock { get; set; }
        public Nullable<decimal> Minimum_Selling_Price { get; set; }
        public Nullable<decimal> Recommended_Selling_Price { get; set; }
        public Nullable<int> Delivery_Lead_Time { get; set; }
        public Nullable<int> NominalCode_Reference { get; set; }
        public string Stock_Category { get; set; }
    }
}
