
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Nominal_codes
{

    public Nominal_codes()
    {

        this.Materials = new HashSet<Material>();

        this.Parts = new HashSet<Part>();

        this.PInvoiceItems = new HashSet<PInvoiceItem>();

        this.PItems = new HashSet<PItem>();

        this.SubContracts = new HashSet<SubContract>();

        this.WOrders = new HashSet<WOrder>();

    }


    public int NominalCode_Reference { get; set; }

    public string Code { get; set; }

    public System.DateTime Creation_Date { get; set; }

    public string Type { get; set; }

    public bool Default_for_type { get; set; }

    public bool Active { get; set; }

    public string Description { get; set; }

    public string Notes { get; set; }



    public virtual ICollection<Material> Materials { get; set; }

    public virtual ICollection<Part> Parts { get; set; }

    public virtual ICollection<PInvoiceItem> PInvoiceItems { get; set; }

    public virtual ICollection<PItem> PItems { get; set; }

    public virtual ICollection<SubContract> SubContracts { get; set; }

    public virtual ICollection<WOrder> WOrders { get; set; }

}

}
