//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonConfomancies_View
    {
        public int NonConformance_Reference { get; set; }
        public string NonConf_Prefix { get; set; }
        public Nullable<int> NonConf_Number { get; set; }
        public string NonConf_Suffix { get; set; }
        public string Description { get; set; }
        public string FullRef { get; set; }
    }
}
