//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_DEPENDENCY
    {
        public decimal NO { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> DEPOPNO { get; set; }
        public Nullable<decimal> DEPORNO { get; set; }
        public Nullable<decimal> TOOPNO { get; set; }
        public Nullable<decimal> TOORNO { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
