//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_OP
    {
        public int NO { get; set; }
        public int SEQNUM { get; set; }
        public double PPARTS { get; set; }
        public int ORNO { get; set; }
        public string NAME { get; set; }
        public int PWPLACE { get; set; }
        public string DESCR { get; set; }
        public Nullable<System.DateTime> STIME { get; set; }
        public Nullable<double> STARTSEC { get; set; }
        public Nullable<System.DateTime> ETIME { get; set; }
        public Nullable<double> ENDESEC { get; set; }
        public int CFLAG { get; set; }
        public Nullable<double> APARTS { get; set; }
        public Nullable<double> ATE { get; set; }
        public Nullable<double> STATUS { get; set; }
        public Nullable<int> OUT { get; set; }
        public Nullable<double> PTR { get; set; }
        public Nullable<double> PTE { get; set; }
        public Nullable<decimal> PTWAIT { get; set; }
        public Nullable<System.DateTime> PSTIMEMIN { get; set; }
        public Nullable<System.DateTime> PETIMEMAX { get; set; }
        public Nullable<decimal> OVERLAPPERC { get; set; }
        public Nullable<decimal> OVERLAP { get; set; }
        public Nullable<decimal> MATMISSING { get; set; }
        public Nullable<System.DateTime> MATETIME { get; set; }
        public string MATREMARK { get; set; }
        public Nullable<decimal> PREPMISSING { get; set; }
        public Nullable<System.DateTime> PREPETIME { get; set; }
        public string PREPREMARK { get; set; }
        public Nullable<decimal> TOOLMISSING { get; set; }
        public Nullable<System.DateTime> TOOLETIME { get; set; }
        public string TOOLREMARK { get; set; }
        public Nullable<decimal> DIV1MISSING { get; set; }
        public Nullable<System.DateTime> DIV1ETIME { get; set; }
        public string DIV1REMARK { get; set; }
        public Nullable<System.DateTime> PSTIMEMAX { get; set; }
        public string BITMAP { get; set; }
        public Nullable<System.DateTime> PETIMEMIN { get; set; }
        public int NCPROG { get; set; }
        public int PARTNO { get; set; }
        public int DRAWNO { get; set; }
        public int OVERLAPDIFF { get; set; }
        public int SPECIAL { get; set; }
        public int TOOLSTIME { get; set; }
        public int OUTCONO { get; set; }
        public int OPINFO { get; set; }
        public int MATERIAL { get; set; }
        public int FIXMISSING { get; set; }
        public int FIXETIME { get; set; }
        public int FIXREMARK { get; set; }
        public Nullable<System.DateTime> LastMDCDate { get; set; }
        public string ARDORGRESOURCE { get; set; }
        public Nullable<decimal> SpeedMode { get; set; }
        public Nullable<decimal> SpeedFactor { get; set; }
        public int ParentPk { get; set; }
        public bool isParent { get; set; }
    }
}
