//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_Lookup_View
    {
        public int Part_Reference { get; set; }
        public string Part_Number { get; set; }
        public string Part_Issue { get; set; }
        public string Name { get; set; }
        public string Specification { get; set; }
        public Nullable<double> Existing_Stock { get; set; }
        public Nullable<double> Existing_Quarantine { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Cost_Quantity { get; set; }
        public string Form { get; set; }
        public string Unit_Of_Measurement { get; set; }
        public string Drawing_Number { get; set; }
        public string Drawing_Issue { get; set; }
        public Nullable<decimal> Minimum_Charge { get; set; }
        public Nullable<double> Uplift_Percentage { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Supplier_Reference { get; set; }
        public string Expiry_Period { get; set; }
        public Nullable<int> Expiry_Interval { get; set; }
    }
}
