
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Part_Material_Form
{

    public string Form { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<bool> Part { get; set; }

    public Nullable<bool> Material { get; set; }

    public string Qty_Calc_Mode { get; set; }

}

}
