
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class PInvoiceSearchView
{

    public int PInvoice_Reference { get; set; }

    public int Supplier_Reference { get; set; }

    public string PI_User_Reference { get; set; }

    public System.DateTime Invoice_Date { get; set; }

    public Nullable<System.DateTime> Invoice_Due_Date { get; set; }

    public Nullable<decimal> Invoice_Total { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> Date_Created { get; set; }

    public Nullable<System.DateTime> Date_Last_Modified { get; set; }

    public byte[] Notes { get; set; }

    public Nullable<int> Last_Modified { get; set; }

    public Nullable<int> Location_Reference { get; set; }

    public Nullable<int> Contact_Reference { get; set; }

    public Nullable<double> Exchange_Rate { get; set; }

    public Nullable<int> Created_By { get; set; }

    public Nullable<int> Owned_By { get; set; }

    public Nullable<decimal> VAT { get; set; }

    public Nullable<decimal> Grand_Total { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> Total_Invoiced_Price { get; set; }

    public bool Exported { get; set; }

    public string Country { get; set; }

    public Nullable<decimal> Converted_Invoice_Total { get; set; }

    public Nullable<decimal> Converted_Discount { get; set; }

    public Nullable<decimal> Converted_VAT { get; set; }

    public Nullable<decimal> Converted_Grand_Total { get; set; }

    public string Currency { get; set; }

    public string Currency_Symbol { get; set; }

}

}
