//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PInvoiceItem_Delivery
    {
        public int PInvoiceItem_Delivery_Reference { get; set; }
        public int PInvoiceItem_Reference { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> PItem_Reference { get; set; }
    }
}
