
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class PItem_Assignments
{

    public int PIA_Reference { get; set; }

    public int PItem_Reference { get; set; }

    public string PIA_Type { get; set; }

    public Nullable<int> WOrder_Reference { get; set; }

    public Nullable<int> WOPart_Reference { get; set; }

    public Nullable<int> WOMaterial_Reference { get; set; }

    public Nullable<int> WOSubContract_Reference { get; set; }

    public Nullable<int> WOTool_Reference { get; set; }

    public double Quantity { get; set; }

    public Nullable<double> Quantity_Received { get; set; }

}

}
