//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PListItem
    {
        public int PListItem_Reference { get; set; }
        public int PList_Reference { get; set; }
        public int Part_Reference { get; set; }
        public Nullable<decimal> RangeUpTo1 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> RangeUpTo2 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> RangeUpTo3 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> RangeUpTo4 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<decimal> RangeUpTo5 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public Nullable<decimal> RangeUpTo6 { get; set; }
        public Nullable<decimal> Price6 { get; set; }
        public Nullable<decimal> RangeUpTo7 { get; set; }
        public Nullable<decimal> Price7 { get; set; }
        public Nullable<decimal> RangeUpTo8 { get; set; }
        public Nullable<decimal> Price8 { get; set; }
    }
}
