
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class PList
{

    public int PList_Reference { get; set; }

    public string Name { get; set; }

    public string Currency_TBA { get; set; }

    public string Mode { get; set; }

    public Nullable<double> Percentage { get; set; }

}

}
