
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class POrderSearchView2
{

    public int POrder_Reference { get; set; }

    public string User_Reference { get; set; }

    public Nullable<int> LineNumber { get; set; }

    public Nullable<int> Supplier_Reference { get; set; }

    public Nullable<System.DateTime> Order_Date { get; set; }

    public string Status { get; set; }

    public Nullable<decimal> Total_Cost { get; set; }

    public string Supplier_Name { get; set; }

    public string Description { get; set; }

    public double Quantity { get; set; }

    public Nullable<decimal> Cost { get; set; }

    public string Drawing_Number { get; set; }

    public string Drawing_Issue { get; set; }

    public string Part_Number { get; set; }

    public string Part_Issue { get; set; }

    public string WO_UserRef_Seq { get; set; }

    public Nullable<System.DateTime> Required_Date { get; set; }

    public string External_Supplier { get; set; }

    public double Quantity_Delivered { get; set; }

    public Nullable<double> Exchange_Rate { get; set; }

    public Nullable<double> Local_Cost { get; set; }

    public int Revision { get; set; }

    public int Ack_Revision { get; set; }

    public Nullable<System.DateTime> Promise_Date { get; set; }

    public string Type { get; set; }

    public string Notes { get; set; }

    public string Contact_Name { get; set; }

    public string Comment { get; set; }

    public Nullable<int> PItem_Reference { get; set; }

    public Nullable<double> Method { get; set; }

    public string Specification { get; set; }

}

}
