
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class POrder_Trace_View
{

    public string User_Reference { get; set; }

    public int DItem_Reference { get; set; }

    public string Description { get; set; }

    public string Drawing_Number { get; set; }

    public string Drawing_Issue { get; set; }

    public double Quantity { get; set; }

    public Nullable<int> WOrder_Reference { get; set; }

    public int PItem_Reference { get; set; }

}

}
