
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Process_Allocated_Stock
{

    public int Record_ID { get; set; }

    public string GUID { get; set; }

    public Nullable<System.DateTime> Creation_Date { get; set; }

    public string Item_Type { get; set; }

    public int Withdrawal_Reference { get; set; }

    public double Quantity { get; set; }

}

}
