//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure
    {
        public int Procedure_Reference { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public byte[] Detail { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> Last_Review { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public bool DefaultProc { get; set; }
        public byte[] Revisions { get; set; }
        public Nullable<System.DateTime> First_Active { get; set; }
        public Nullable<System.DateTime> Last_Active { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public string UDF07 { get; set; }
        public string UDF08 { get; set; }
        public Nullable<System.DateTime> UDFD01 { get; set; }
        public Nullable<System.DateTime> UDFD02 { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public string Status { get; set; }
        public string Equipment_To_Use { get; set; }
        public string Further_Notes { get; set; }
        public string Maint_Or_Calibration_Spec_Notes { get; set; }
    }
}
