
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class QSubDiscountView
{

    public Nullable<double> Quantity { get; set; }

    public Nullable<double> Discount { get; set; }

    public Nullable<int> Customer_Reference { get; set; }

    public string Part_Number { get; set; }

    public string Part_Issue { get; set; }

    public int Quote_Reference { get; set; }

}

}
