//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskCategory
    {
        public int Risk_Category_Reference { get; set; }
        public string Risk_Level { get; set; }
        public string Risk_Name { get; set; }
        public byte[] Notes { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Risk_Colour { get; set; }
    }
}
