//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Deviation_View
    {
        public Nullable<int> worder_reference { get; set; }
        public Nullable<System.DateTime> old_schedule_date { get; set; }
        public Nullable<System.DateTime> new_schedule_date { get; set; }
        public string User_Reference { get; set; }
        public Nullable<System.DateTime> Delivery { get; set; }
        public string Description { get; set; }
        public string Part_number { get; set; }
        public string Part_Issue { get; set; }
        public Nullable<int> Customer_Reference { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Name { get; set; }
    }
}
