//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_Activity_Code
    {
        public int Activity_Code_Reference { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Machine_Related { get; set; }
        public Nullable<bool> Interrupt_Other_Activities { get; set; }
        public Nullable<bool> Regular { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> IconIndex { get; set; }
    }
}
