
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Subcontract_Usage
{

    public int WOSubcontract_Reference { get; set; }

    public int Subcontract_Reference { get; set; }

    public Nullable<System.DateTime> Received_Date { get; set; }

    public Nullable<double> Quantity { get; set; }

    public Nullable<int> STrace_Reference { get; set; }

}

}
