
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Supplier
{

    public int Supplier_Reference { get; set; }

    public string External_Supplier { get; set; }

    public string Name { get; set; }

    public string Terms { get; set; }

    public string Quality_Program { get; set; }

    public bool Trace { get; set; }

    public Nullable<System.DateTime> Last_Audit { get; set; }

    public string Notes { get; set; }

    public Nullable<int> Contact_Reference { get; set; }

    public Nullable<int> Location_Reference { get; set; }

    public int Client_Reference { get; set; }

    public System.DateTime Date_Created { get; set; }

    public System.DateTime Date_Last_Modified { get; set; }

    public bool Approved { get; set; }

    public string Supplying { get; set; }

    public Nullable<int> Created_By { get; set; }

    public Nullable<int> Owned_By { get; set; }

    public Nullable<int> Last_Modified { get; set; }

    public Nullable<int> VAT_Reference { get; set; }

    public string Supplier_Status { get; set; }

    public string Country_Code { get; set; }

    public Nullable<int> NumFileAttachments { get; set; }

    public Nullable<int> NumBrokenLinks { get; set; }

    public Nullable<bool> CoC_Required { get; set; }

    public Nullable<int> Invoice_Contact_Reference { get; set; }

    public Nullable<int> Invoice_Location_Reference { get; set; }

    public Nullable<int> Supplier_Rating { get; set; }

    public Nullable<bool> Supply_Parts { get; set; }

    public Nullable<bool> Supply_Materials { get; set; }

    public Nullable<bool> Supply_SubContract { get; set; }

    public Nullable<bool> Supply_Tooling { get; set; }

    public string UDF01 { get; set; }

    public string UDF02 { get; set; }

    public string UDF03 { get; set; }

    public string UDFF01 { get; set; }

    public string UDF04 { get; set; }

    public string UDF05 { get; set; }

    public string UDF06 { get; set; }

    public string UDF07 { get; set; }

    public string UDF08 { get; set; }

    public string UDF09 { get; set; }

    public string UDF10 { get; set; }

}

}
