//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int Tag_Reference { get; set; }
        public string From_Entity_Type { get; set; }
        public int From_Entity_Reference { get; set; }
        public string From_Text { get; set; }
        public string To_Entity_Type { get; set; }
        public Nullable<int> To_Entity_Reference { get; set; }
        public string To_Text { get; set; }
        public Nullable<int> Colour { get; set; }
        public Nullable<bool> Alert { get; set; }
        public string AlertType { get; set; }
        public Nullable<System.DateTime> Active_From { get; set; }
        public Nullable<System.DateTime> Active_To { get; set; }
        public Nullable<bool> Never_Expires { get; set; }
        public Nullable<bool> Blink { get; set; }
    }
}
