//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Assignments
    {
        public int Task_Assignment_Reference { get; set; }
        public int Task_Reference { get; set; }
        public int Employee_Reference { get; set; }
        public bool Seen { get; set; }
        public string Task_Colour { get; set; }
        public Nullable<bool> CC { get; set; }
    }
}
