//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TED_Data
    {
        public int Data_Reference { get; set; }
        public int Table_Reference { get; set; }
        public Nullable<int> Entity_Reference { get; set; }
        public string UDF_001 { get; set; }
        public string UDF_002 { get; set; }
        public string UDF_003 { get; set; }
        public string UDF_004 { get; set; }
        public string UDF_005 { get; set; }
        public string UDF_006 { get; set; }
        public string UDF_007 { get; set; }
        public string UDF_008 { get; set; }
        public string UDF_009 { get; set; }
        public string UDF_010 { get; set; }
        public string UDF_011 { get; set; }
        public string UDF_012 { get; set; }
        public string UDF_013 { get; set; }
        public string UDF_014 { get; set; }
        public string UDF_015 { get; set; }
        public string UDF_016 { get; set; }
        public string UDF_017 { get; set; }
        public string UDF_018 { get; set; }
        public string UDF_019 { get; set; }
        public string UDF_020 { get; set; }
        public string UDF_021 { get; set; }
        public string UDF_022 { get; set; }
        public string UDF_023 { get; set; }
        public string UDF_024 { get; set; }
        public string UDF_025 { get; set; }
        public string UDF_026 { get; set; }
        public string UDF_027 { get; set; }
        public string UDF_028 { get; set; }
        public string UDF_029 { get; set; }
        public string UDF_030 { get; set; }
        public string UDF_031 { get; set; }
        public string UDF_032 { get; set; }
        public string UDF_033 { get; set; }
        public string UDF_034 { get; set; }
        public string UDF_035 { get; set; }
        public string UDF_036 { get; set; }
        public string UDF_037 { get; set; }
        public string UDF_038 { get; set; }
        public string UDF_039 { get; set; }
        public string UDF_040 { get; set; }
        public string UDF_041 { get; set; }
        public string UDF_042 { get; set; }
        public string UDF_043 { get; set; }
        public string UDF_044 { get; set; }
        public string UDF_045 { get; set; }
        public string UDF_046 { get; set; }
        public string UDF_047 { get; set; }
        public string UDF_048 { get; set; }
        public string UDF_049 { get; set; }
        public string UDF_050 { get; set; }
        public string UDF_051 { get; set; }
        public string UDF_052 { get; set; }
        public string UDF_053 { get; set; }
        public string UDF_054 { get; set; }
        public string UDF_055 { get; set; }
        public string UDF_056 { get; set; }
        public string UDF_057 { get; set; }
        public string UDF_058 { get; set; }
        public string UDF_059 { get; set; }
        public string UDF_060 { get; set; }
        public string UDF_061 { get; set; }
        public string UDF_062 { get; set; }
        public string UDF_063 { get; set; }
        public string UDF_064 { get; set; }
        public string UDF_065 { get; set; }
        public string UDF_066 { get; set; }
        public string UDF_067 { get; set; }
        public string UDF_068 { get; set; }
        public string UDF_069 { get; set; }
        public string UDF_070 { get; set; }
        public string UDF_071 { get; set; }
        public string UDF_072 { get; set; }
        public string UDF_073 { get; set; }
        public string UDF_074 { get; set; }
        public string UDF_075 { get; set; }
        public string UDF_076 { get; set; }
        public string UDF_077 { get; set; }
        public string UDF_078 { get; set; }
        public string UDF_079 { get; set; }
        public string UDF_080 { get; set; }
        public string UDF_081 { get; set; }
        public string UDF_082 { get; set; }
        public string UDF_083 { get; set; }
        public string UDF_084 { get; set; }
        public string UDF_085 { get; set; }
        public string UDF_086 { get; set; }
        public string UDF_087 { get; set; }
        public string UDF_088 { get; set; }
        public string UDF_089 { get; set; }
        public string UDF_090 { get; set; }
        public string UDF_091 { get; set; }
        public string UDF_092 { get; set; }
        public string UDF_093 { get; set; }
        public string UDF_094 { get; set; }
        public string UDF_095 { get; set; }
        public string UDF_096 { get; set; }
        public string UDF_097 { get; set; }
        public string UDF_098 { get; set; }
        public string UDF_099 { get; set; }
        public string UDF_100 { get; set; }
        public string UDF_101 { get; set; }
        public string UDF_102 { get; set; }
        public string UDF_103 { get; set; }
        public string UDF_104 { get; set; }
        public string UDF_105 { get; set; }
        public string UDF_106 { get; set; }
        public string UDF_107 { get; set; }
        public string UDF_108 { get; set; }
        public string UDF_109 { get; set; }
        public string UDF_110 { get; set; }
        public string UDF_111 { get; set; }
        public string UDF_112 { get; set; }
        public string UDF_113 { get; set; }
        public string UDF_114 { get; set; }
        public string UDF_115 { get; set; }
        public string UDF_116 { get; set; }
        public string UDF_117 { get; set; }
        public string UDF_118 { get; set; }
        public string UDF_119 { get; set; }
        public string UDF_120 { get; set; }
        public string UDF_121 { get; set; }
        public string UDF_122 { get; set; }
        public string UDF_123 { get; set; }
        public string UDF_124 { get; set; }
        public string UDF_125 { get; set; }
        public string UDF_126 { get; set; }
        public string UDF_127 { get; set; }
        public string UDF_128 { get; set; }
        public string UDF_129 { get; set; }
        public string UDF_130 { get; set; }
        public string UDF_131 { get; set; }
        public string UDF_132 { get; set; }
        public string UDF_133 { get; set; }
        public string UDF_134 { get; set; }
        public string UDF_135 { get; set; }
        public string UDF_136 { get; set; }
        public string UDF_137 { get; set; }
        public string UDF_138 { get; set; }
        public string UDF_139 { get; set; }
        public string UDF_140 { get; set; }
        public string UDF_141 { get; set; }
        public string UDF_142 { get; set; }
        public string UDF_143 { get; set; }
        public string UDF_144 { get; set; }
        public string UDF_145 { get; set; }
        public string UDF_146 { get; set; }
        public string UDF_147 { get; set; }
        public string UDF_148 { get; set; }
        public string UDF_149 { get; set; }
        public string UDF_150 { get; set; }
        public Nullable<System.DateTime> UDF_Date_01 { get; set; }
        public Nullable<System.DateTime> UDF_Date_02 { get; set; }
        public Nullable<System.DateTime> UDF_Date_03 { get; set; }
        public Nullable<System.DateTime> UDF_Date_04 { get; set; }
        public Nullable<System.DateTime> UDF_Date_05 { get; set; }
        public Nullable<System.DateTime> UDF_Date_06 { get; set; }
        public Nullable<System.DateTime> UDF_Date_07 { get; set; }
        public Nullable<System.DateTime> UDF_Date_08 { get; set; }
        public Nullable<System.DateTime> UDF_Date_09 { get; set; }
        public Nullable<System.DateTime> UDF_Date_10 { get; set; }
        public string Status { get; set; }
    }
}
