//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNotification
    {
        public int Notification_Reference { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Entity_Type { get; set; }
        public int Entity_Reference { get; set; }
        public string Notification_Type { get; set; }
        public string Notification_Definition { get; set; }
        public string Description { get; set; }
        public Nullable<int> For_Role { get; set; }
        public Nullable<int> For_Employee { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date_Completed { get; set; }
        public Nullable<System.DateTime> Auto_Expiry_Date { get; set; }
        public Nullable<int> Created_By_SPID { get; set; }
    }
}
