
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class TQ_InspRec
{

    public int InspRec_Reference { get; set; }

    public Nullable<int> WOTimes_Reference { get; set; }

    public Nullable<int> WOWCentre_Reference { get; set; }

    public Nullable<int> Batch_Reference { get; set; }

    public Nullable<decimal> Qty_Inspected { get; set; }

    public Nullable<decimal> Qty_Accepted { get; set; }

    public Nullable<decimal> Qty_Rejected { get; set; }

    public string Notes { get; set; }

    public Nullable<int> Created_By { get; set; }

    public System.DateTime Date_Inspected { get; set; }

    public Nullable<int> Reject_Reference { get; set; }



    public virtual WOOperAct WOOperAct { get; set; }

}

}
