//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRemote
    {
        public int Remote_Reference { get; set; }
        public string For_Product { get; set; }
        public string For_Machine { get; set; }
        public string Instruction { get; set; }
        public string Entity_Type { get; set; }
        public Nullable<int> Entity_Reference { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    }
}
