//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRFQ
    {
        public int RFQ_Reference { get; set; }
        public string User_Reference { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public Nullable<int> Last_Modified { get; set; }
        public string UDFF01 { get; set; }
        public string UDFF02 { get; set; }
        public string UDFF03 { get; set; }
        public string UDFF04 { get; set; }
        public string UDFF05 { get; set; }
        public string UDFF06 { get; set; }
    }
}
