//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRFQ_Responses
    {
        public int RFQResponse_Reference { get; set; }
        public int RFQItem_Reference { get; set; }
        public int Supplier_Reference { get; set; }
        public Nullable<decimal> Quoted_Price { get; set; }
        public Nullable<double> Qty { get; set; }
        public string UOM { get; set; }
        public Nullable<int> Lead_Time_Days { get; set; }
        public string Note { get; set; }
        public bool Declined { get; set; }
        public bool Excluded { get; set; }
        public Nullable<decimal> Supplier_Quoted_Price { get; set; }
    }
}
