
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class TRFQ_Suppliers
{

    public int RFQSuppliers_Reference { get; set; }

    public int RFQ_Reference { get; set; }

    public int Supplier_Reference { get; set; }

    public Nullable<int> Supplier_Index { get; set; }

    public Nullable<int> Contact_Reference { get; set; }

    public Nullable<int> Location_Reference { get; set; }

}

}
