
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class TRFQ_Sources
{

    public int RFQSource_Reference { get; set; }

    public int RFQItem_Reference { get; set; }

    public string Source_Order_Type { get; set; }

    public decimal Qty { get; set; }

    public Nullable<int> Quote_Reference { get; set; }

    public Nullable<int> QMaterial_Reference { get; set; }

    public Nullable<int> QPart_Reference { get; set; }

    public Nullable<int> QSubcontract_Reference { get; set; }

    public Nullable<int> QTool_Reference { get; set; }

    public Nullable<int> WOrder_Reference { get; set; }

    public Nullable<int> WOMaterial_Reference { get; set; }

    public Nullable<int> WOPart_Reference { get; set; }

    public Nullable<int> WOSubcontract_Reference { get; set; }

    public Nullable<int> WOTool_Reference { get; set; }

    public int Source_Order_Type_Sort { get; set; }

}

}
