
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Tricorn_Access_Flags
{

    public Tricorn_Access_Flags()
    {

        this.Tricorn_Access_Rights = new HashSet<Tricorn_Access_Rights>();

    }


    public int TAF_Record_ID { get; set; }

    public string Description { get; set; }

    public string Extended_Description { get; set; }

    public bool Default_Value { get; set; }

    public string Function_Group { get; set; }



    public virtual ICollection<Tricorn_Access_Rights> Tricorn_Access_Rights { get; set; }

}

}
