//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tricorn_Logged_Tables
    {
        public Tricorn_Logged_Tables()
        {
            this.Tricorn_Logged_Fields = new HashSet<Tricorn_Logged_Fields>();
        }
    
        public int Logged_Table_ID { get; set; }
        public string Logged_Table_Name { get; set; }
        public bool Log_Insert { get; set; }
        public bool Log_Update { get; set; }
        public bool Log_Delete { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Tricorn_Logged_Fields> Tricorn_Logged_Fields { get; set; }
    }
}
