//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tricorn_Event_Log
    {
        public int Record_ID { get; set; }
        public string Event_Type { get; set; }
        public string ProgramName { get; set; }
        public int User_Record_ID { get; set; }
        public string Login_ID { get; set; }
        public string PC_Name { get; set; }
        public System.DateTime Event_DateTime { get; set; }
        public string Table_Name { get; set; }
        public Nullable<int> Record_Reference { get; set; }
        public string Action_Type { get; set; }
        public string Before_Action { get; set; }
        public string After_Action { get; set; }
        public string Parent_Table { get; set; }
        public string Parent_Reference_Field { get; set; }
        public Nullable<int> Parent_Reference_Value { get; set; }
        public string Parent_User_Reference { get; set; }
    }
}
