//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tricorn_Logged_Fields
    {
        public int Logged_Field_ID { get; set; }
        public int Logged_Table_ID { get; set; }
        public string Logged_Field_Name { get; set; }
    
        public virtual Tricorn_Logged_Fields Tricorn_Logged_Fields1 { get; set; }
        public virtual Tricorn_Logged_Fields Tricorn_Logged_Fields2 { get; set; }
        public virtual Tricorn_Logged_Tables Tricorn_Logged_Tables { get; set; }
    }
}
