//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TricornEntities : DbContext
    {
        public TricornEntities()
            : base("name=TricornEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ART_CUSTOMER> ART_CUSTOMER { get; set; }
        public DbSet<ART_DELQUOTATION> ART_DELQUOTATION { get; set; }
        public DbSet<ART_LTEXT> ART_LTEXT { get; set; }
        public DbSet<ART_PLNAME> ART_PLNAME { get; set; }
        public DbSet<Audit> Audits { get; set; }
        public DbSet<AuditItem> AuditItems { get; set; }
        public DbSet<Batch> Batches { get; set; }
        public DbSet<CA_CAPACITY> CA_CAPACITY { get; set; }
        public DbSet<CA_HOLIDAY> CA_HOLIDAY { get; set; }
        public DbSet<CA_WEEKPLAN> CA_WEEKPLAN { get; set; }
        public DbSet<CalibKeysDetail> CalibKeysDetails { get; set; }
        public DbSet<CalibrationEquipment> CalibrationEquipments { get; set; }
        public DbSet<CalibrationHistory> CalibrationHistories { get; set; }
        public DbSet<CalibrationProcedure> CalibrationProcedures { get; set; }
        public DbSet<CalibrationUsage> CalibrationUsages { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Complaint> Complaints { get; set; }
        public DbSet<Concession> Concessions { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Cost_Centre> Cost_Centre { get; set; }
        public DbSet<CP_Weekly> CP_Weekly { get; set; }
        public DbSet<CU_ACCOUNT> CU_ACCOUNT { get; set; }
        public DbSet<CU_BEM> CU_BEM { get; set; }
        public DbSet<CU_CNTRY> CU_CNTRY { get; set; }
        public DbSet<CU_COTYP> CU_COTYP { get; set; }
        public DbSet<CU_INFO> CU_INFO { get; set; }
        public DbSet<CU_MAIL> CU_MAIL { get; set; }
        public DbSet<CU_PERS> CU_PERS { get; set; }
        public DbSet<CU_VERS> CU_VERS { get; set; }
        public DbSet<CustomCommand> CustomCommands { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Customer_Currency> Customer_Currency { get; set; }
        public DbSet<CustomerSatisfaction> CustomerSatisfactions { get; set; }
        public DbSet<CustomerSatisfactionDetail> CustomerSatisfactionDetails { get; set; }
        public DbSet<DefaultWorkingHr> DefaultWorkingHrs { get; set; }
        public DbSet<Discount> Discounts { get; set; }
        public DbSet<DItem> DItems { get; set; }
        public DbSet<DItemBuiltPartTrace> DItemBuiltPartTraces { get; set; }
        public DbSet<DItemMatTrace> DItemMatTraces { get; set; }
        public DbSet<DItemPartTrace> DItemPartTraces { get; set; }
        public DbSet<DItemSubConTrace> DItemSubConTraces { get; set; }
        public DbSet<DItemToolTrace> DItemToolTraces { get; set; }
        public DbSet<DMethod> DMethods { get; set; }
        public DbSet<DNote> DNotes { get; set; }
        public DbSet<DocNote> DocNotes { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<EAddress> EAddresses { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Employee_Details> Employee_Details { get; set; }
        public DbSet<FactoryDayPlan> FactoryDayPlans { get; set; }
        public DbSet<FAG_DETAIL> FAG_DETAIL { get; set; }
        public DbSet<FAG_SALESMAN> FAG_SALESMAN { get; set; }
        public DbSet<FAG_TRANSACTIONLOCKING> FAG_TRANSACTIONLOCKING { get; set; }
        public DbSet<FAG_UNILOG> FAG_UNILOG { get; set; }
        public DbSet<FI_ACCOUNT> FI_ACCOUNT { get; set; }
        public DbSet<GKN_PROJECT> GKN_PROJECT { get; set; }
        public DbSet<IN_KASSE> IN_KASSE { get; set; }
        public DbSet<InvItem> InvItems { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<IS_CAL> IS_CAL { get; set; }
        public DbSet<IS_NUM> IS_NUM { get; set; }
        public DbSet<IS_SETUP> IS_SETUP { get; set; }
        public DbSet<LB_DC> LB_DC { get; set; }
        public DbSet<LB_FUNCTION> LB_FUNCTION { get; set; }
        public DbSet<License> Licenses { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<MaintenanceHistory> MaintenanceHistories { get; set; }
        public DbSet<MaintenanceMachine> MaintenanceMachines { get; set; }
        public DbSet<MaintenanceProcedure> MaintenanceProcedures { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<MDC_EVENTSTRUCT> MDC_EVENTSTRUCT { get; set; }
        public DbSet<MDC_FUNCTIONMAPPING> MDC_FUNCTIONMAPPING { get; set; }
        public DbSet<MDC_TERMINALID> MDC_TERMINALID { get; set; }
        public DbSet<MStock> MStocks { get; set; }
        public DbSet<MWithdrawal> MWithdrawals { get; set; }
        public DbSet<Nominal_codes> Nominal_codes { get; set; }
        public DbSet<Nonconformancy> Nonconformancies { get; set; }
        public DbSet<Notifier> Notifiers { get; set; }
        public DbSet<OG_ORGA> OG_ORGA { get; set; }
        public DbSet<OG_ORGADOC> OG_ORGADOC { get; set; }
        public DbSet<OP_CNC> OP_CNC { get; set; }
        public DbSet<OP_SPC> OP_SPC { get; set; }
        public DbSet<OR_ART> OR_ART { get; set; }
        public DbSet<OR_CALC> OR_CALC { get; set; }
        public DbSet<OR_CHARGE> OR_CHARGE { get; set; }
        public DbSet<OR_GRPTYP> OR_GRPTYP { get; set; }
        public DbSet<OR_OPNAME> OR_OPNAME { get; set; }
        public DbSet<OR_OPTYPE> OR_OPTYPE { get; set; }
        public DbSet<OR_PROJ> OR_PROJ { get; set; }
        public DbSet<OR_SERIAL> OR_SERIAL { get; set; }
        public DbSet<Order_Events> Order_Events { get; set; }
        public DbSet<PA_ARTGRP> PA_ARTGRP { get; set; }
        public DbSet<PA_ARTHIS> PA_ARTHIS { get; set; }
        public DbSet<PA_ARTLIEF> PA_ARTLIEF { get; set; }
        public DbSet<PA_ARTPOS> PA_ARTPOS { get; set; }
        public DbSet<PA_ARTTYP> PA_ARTTYP { get; set; }
        public DbSet<PA_DPD> PA_DPD { get; set; }
        public DbSet<PA_FIBU> PA_FIBU { get; set; }
        public DbSet<PA_FIT> PA_FIT { get; set; }
        public DbSet<PA_PACKAGING> PA_PACKAGING { get; set; }
        public DbSet<PA_PAPER> PA_PAPER { get; set; }
        public DbSet<PA_POSIT> PA_POSIT { get; set; }
        public DbSet<PA_STLB> PA_STLB { get; set; }
        public DbSet<PA_TEXTE> PA_TEXTE { get; set; }
        public DbSet<Part> Parts { get; set; }
        public DbSet<PartTrace> PartTraces { get; set; }
        public DbSet<PE_GROUP> PE_GROUP { get; set; }
        public DbSet<PE_MAPPING> PE_MAPPING { get; set; }
        public DbSet<PE_WORK> PE_WORK { get; set; }
        public DbSet<PE_WPLACE> PE_WPLACE { get; set; }
        public DbSet<PItem> PItems { get; set; }
        public DbSet<POrder> POrders { get; set; }
        public DbSet<PRM_LAYOUTS> PRM_LAYOUTS { get; set; }
        public DbSet<PRM_OBJECTS> PRM_OBJECTS { get; set; }
        public DbSet<PRM_PERS> PRM_PERS { get; set; }
        public DbSet<PRM_SIMU> PRM_SIMU { get; set; }
        public DbSet<PRM_TRANSBOX> PRM_TRANSBOX { get; set; }
        public DbSet<PRM_TRANSSYS> PRM_TRANSSYS { get; set; }
        public DbSet<PRM_WAYCACHE> PRM_WAYCACHE { get; set; }
        public DbSet<Procedure> Procedures { get; set; }
        public DbSet<PStock> PStocks { get; set; }
        public DbSet<PW_PASS> PW_PASS { get; set; }
        public DbSet<PWithdrawal> PWithdrawals { get; set; }
        public DbSet<QComponent> QComponents { get; set; }
        public DbSet<QMaterial> QMaterials { get; set; }
        public DbSet<QPart> QParts { get; set; }
        public DbSet<QSubContract> QSubContracts { get; set; }
        public DbSet<QTool> QTools { get; set; }
        public DbSet<Quote> Quotes { get; set; }
        public DbSet<QWCentre> QWCentres { get; set; }
        public DbSet<rb_field> rb_field { get; set; }
        public DbSet<rb_folder> rb_folder { get; set; }
        public DbSet<rb_item> rb_item { get; set; }
        public DbSet<rb_join> rb_join { get; set; }
        public DbSet<rb_table> rb_table { get; set; }
        public DbSet<ReasonCodeType> ReasonCodeTypes { get; set; }
        public DbSet<RecordKey> RecordKeys { get; set; }
        public DbSet<RejectCategory> RejectCategories { get; set; }
        public DbSet<Reject> Rejects { get; set; }
        public DbSet<RFQ> RFQs { get; set; }
        public DbSet<RFQ_Item> RFQ_Item { get; set; }
        public DbSet<RFQ_Plan> RFQ_Plan { get; set; }
        public DbSet<SatisfactionCategory> SatisfactionCategories { get; set; }
        public DbSet<SFDC_CLIENT_RECENT_USERS> SFDC_CLIENT_RECENT_USERS { get; set; }
        public DbSet<SFDC_CLIENT_WORKCENTRES> SFDC_CLIENT_WORKCENTRES { get; set; }
        public DbSet<SFDC_CLIENTS> SFDC_CLIENTS { get; set; }
        public DbSet<SFDC_GROUPS> SFDC_GROUPS { get; set; }
        public DbSet<SH_DPD> SH_DPD { get; set; }
        public DbSet<ST_PLACE> ST_PLACE { get; set; }
        public DbSet<ST_STOCK> ST_STOCK { get; set; }
        public DbSet<Stock_Categories> Stock_Categories { get; set; }
        public DbSet<STrace> STraces { get; set; }
        public DbSet<SubContract> SubContracts { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<SupplierPerformance> SupplierPerformances { get; set; }
        public DbSet<System_Codes> System_Codes { get; set; }
        public DbSet<Training> Trainings { get; set; }
        public DbSet<Tricorn_User_Acct> Tricorn_User_Acct { get; set; }
        public DbSet<TricornSession> TricornSessions { get; set; }
        public DbSet<TTrace> TTraces { get; set; }
        public DbSet<UpgradeInfo> UpgradeInfoes { get; set; }
        public DbSet<VAT_Rates> VAT_Rates { get; set; }
        public DbSet<Warning> Warnings { get; set; }
        public DbSet<WCentre> WCentres { get; set; }
        public DbSet<WH_INT> WH_INT { get; set; }
        public DbSet<WOComponent> WOComponents { get; set; }
        public DbSet<WOInspection> WOInspections { get; set; }
        public DbSet<WOMaterial> WOMaterials { get; set; }
        public DbSet<WOOperAct> WOOperActs { get; set; }
        public DbSet<WOPart> WOParts { get; set; }
        public DbSet<WOrder> WOrders { get; set; }
        public DbSet<WOSubContract> WOSubContracts { get; set; }
        public DbSet<WOTool> WOTools { get; set; }
        public DbSet<WOWCentre> WOWCentres { get; set; }
        public DbSet<WP_GROUP> WP_GROUP { get; set; }
        public DbSet<WP_MAGRP> WP_MAGRP { get; set; }
        public DbSet<Break_Times> Break_Times { get; set; }
        public DbSet<DBVersion> DBVersions { get; set; }
        public DbSet<DiscountDetail> DiscountDetails { get; set; }
        public DbSet<JIS_ADRESSEN> JIS_ADRESSEN { get; set; }
        public DbSet<JIS_FERTIGUNG> JIS_FERTIGUNG { get; set; }
        public DbSet<option> options { get; set; }
        public DbSet<OR_FRAG> OR_FRAG { get; set; }
        public DbSet<Param> Params { get; set; }
        public DbSet<PRM_VECTORMAP> PRM_VECTORMAP { get; set; }
        public DbSet<WCentreCost> WCentreCosts { get; set; }
        public DbSet<AuditFullView> AuditFullViews { get; set; }
        public DbSet<CalibEquipFullView> CalibEquipFullViews { get; set; }
        public DbSet<CalibProcFullView> CalibProcFullViews { get; set; }
        public DbSet<ComplaintFullView> ComplaintFullViews { get; set; }
        public DbSet<Complaints_View> Complaints_View { get; set; }
        public DbSet<Concession_View> Concession_View { get; set; }
        public DbSet<ConcessionsFullView> ConcessionsFullViews { get; set; }
        public DbSet<CU_COMP> CU_COMP { get; set; }
        public DbSet<DiscountView> DiscountViews { get; set; }
        public DbSet<DNoteSearchView> DNoteSearchViews { get; set; }
        public DbSet<EU_Material_MRP> EU_Material_MRP { get; set; }
        public DbSet<EU_Parts_TItle_MRP> EU_Parts_TItle_MRP { get; set; }
        public DbSet<EU_Title_Mrp> EU_Title_Mrp { get; set; }
        public DbSet<InvoiceSearchView> InvoiceSearchViews { get; set; }
        public DbSet<Kpi_GanntData> Kpi_GanntData { get; set; }
        public DbSet<Kpi_GanntView> Kpi_GanntView { get; set; }
        public DbSet<KPI_OperatorActive> KPI_OperatorActive { get; set; }
        public DbSet<KPI_OperatorInactive> KPI_OperatorInactive { get; set; }
        public DbSet<KPI_OperatorProductivity> KPI_OperatorProductivity { get; set; }
        public DbSet<KPI_OPERATORTIMES> KPI_OPERATORTIMES { get; set; }
        public DbSet<MaintMachFullView> MaintMachFullViews { get; set; }
        public DbSet<MaintProcFullView> MaintProcFullViews { get; set; }
        public DbSet<MaterialSearchView> MaterialSearchViews { get; set; }
        public DbSet<MStock_View> MStock_View { get; set; }
        public DbSet<NonConfFullView> NonConfFullViews { get; set; }
        public DbSet<NonConfomancies_View> NonConfomancies_View { get; set; }
        public DbSet<OR_DEPENDENCY> OR_DEPENDENCY { get; set; }
        public DbSet<OR_OP> OR_OP { get; set; }
        public DbSet<OR_ORDER> OR_ORDER { get; set; }
        public DbSet<OrderIndex> OrderIndexes { get; set; }
        public DbSet<Part_Lookup_View> Part_Lookup_View { get; set; }
        public DbSet<PartSearchView> PartSearchViews { get; set; }
        public DbSet<POrder_Trace_View> POrder_Trace_View { get; set; }
        public DbSet<POrder_WOrder_View> POrder_WOrder_View { get; set; }
        public DbSet<POrderSearchView> POrderSearchViews { get; set; }
        public DbSet<POrderSearchView2> POrderSearchView2 { get; set; }
        public DbSet<ProceduresFullView> ProceduresFullViews { get; set; }
        public DbSet<PStock_View> PStock_View { get; set; }
        public DbSet<QSubDiscountView> QSubDiscountViews { get; set; }
        public DbSet<Rejects_View> Rejects_View { get; set; }
        public DbSet<RejectsFullView> RejectsFullViews { get; set; }
        public DbSet<Schedule_Deviation_View> Schedule_Deviation_View { get; set; }
        public DbSet<SuppPerfFullView> SuppPerfFullViews { get; set; }
        public DbSet<today> todays { get; set; }
        public DbSet<TrainingFullView> TrainingFullViews { get; set; }
        public DbSet<WOInspectFullView> WOInspectFullViews { get; set; }
        public DbSet<WOrder_All_View> WOrder_All_View { get; set; }
        public DbSet<WORDER_SCHEDULE_VIEW> WORDER_SCHEDULE_VIEW { get; set; }
        public DbSet<WOrder_Templates_View> WOrder_Templates_View { get; set; }
        public DbSet<WOSubDiscountView> WOSubDiscountViews { get; set; }
        public DbSet<WP_MA1> WP_MA1 { get; set; }
    
        public virtual int ChangeQuoteQuantity(Nullable<int> quoteRefToChange)
        {
            var quoteRefToChangeParameter = quoteRefToChange.HasValue ?
                new ObjectParameter("QuoteRefToChange", quoteRefToChange) :
                new ObjectParameter("QuoteRefToChange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeQuoteQuantity", quoteRefToChangeParameter);
        }
    
        public virtual int ChangeWOQuantity(Nullable<int> wORefToChange)
        {
            var wORefToChangeParameter = wORefToChange.HasValue ?
                new ObjectParameter("WORefToChange", wORefToChange) :
                new ObjectParameter("WORefToChange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeWOQuantity", wORefToChangeParameter);
        }
    
        public virtual int CloseOpenWooperacts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloseOpenWooperacts");
        }
    
        public virtual int CloseWooperactsOnTimeOut(Nullable<int> minsRunning)
        {
            var minsRunningParameter = minsRunning.HasValue ?
                new ObjectParameter("minsRunning", minsRunning) :
                new ObjectParameter("minsRunning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloseWooperactsOnTimeOut", minsRunningParameter);
        }
    
        public virtual int CopyAMaterial(Nullable<int> materialRefToCopy)
        {
            var materialRefToCopyParameter = materialRefToCopy.HasValue ?
                new ObjectParameter("MaterialRefToCopy", materialRefToCopy) :
                new ObjectParameter("MaterialRefToCopy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyAMaterial", materialRefToCopyParameter);
        }
    
        public virtual int CopyInvItem(Nullable<int> invoiceRefToCopy, Nullable<int> newInvoiceRef)
        {
            var invoiceRefToCopyParameter = invoiceRefToCopy.HasValue ?
                new ObjectParameter("InvoiceRefToCopy", invoiceRefToCopy) :
                new ObjectParameter("InvoiceRefToCopy", typeof(int));
    
            var newInvoiceRefParameter = newInvoiceRef.HasValue ?
                new ObjectParameter("NewInvoiceRef", newInvoiceRef) :
                new ObjectParameter("NewInvoiceRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyInvItem", invoiceRefToCopyParameter, newInvoiceRefParameter);
        }
    
        public virtual int CopyInvoiceToCNote(Nullable<int> invoiceRefToCopy, string user_Reference)
        {
            var invoiceRefToCopyParameter = invoiceRefToCopy.HasValue ?
                new ObjectParameter("InvoiceRefToCopy", invoiceRefToCopy) :
                new ObjectParameter("InvoiceRefToCopy", typeof(int));
    
            var user_ReferenceParameter = user_Reference != null ?
                new ObjectParameter("User_Reference", user_Reference) :
                new ObjectParameter("User_Reference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyInvoiceToCNote", invoiceRefToCopyParameter, user_ReferenceParameter);
        }
    
        public virtual int CopyQMaterial(Nullable<int> quoteRefToCopy, Nullable<int> newQuoteRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQMaterial", quoteRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int CopyQMaterialToWOMaterial(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQMaterialToWOMaterial", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopyQPart(Nullable<int> quoteRefToCopy, Nullable<int> newQuoteRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQPart", quoteRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int CopyQPartToWOPart(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQPartToWOPart", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopyQSubContract(Nullable<int> quoteRefToCopy, Nullable<int> newQuoteRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQSubContract", quoteRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int CopyQSubContractToWOSubContract(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQSubContractToWOSubContract", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopyQTool(Nullable<int> quoteRefToCopy, Nullable<int> newQuoteRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQTool", quoteRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int CopyQuote(Nullable<int> quoteRefToCopy, Nullable<int> sequence, string user_Reference, string group_Reference, string status, Nullable<bool> main, Nullable<bool> copy_Components, Nullable<double> quantity, Nullable<bool> explode, Nullable<int> user_id, Nullable<double> order_Quantity)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var sequenceParameter = sequence.HasValue ?
                new ObjectParameter("Sequence", sequence) :
                new ObjectParameter("Sequence", typeof(int));
    
            var user_ReferenceParameter = user_Reference != null ?
                new ObjectParameter("User_Reference", user_Reference) :
                new ObjectParameter("User_Reference", typeof(string));
    
            var group_ReferenceParameter = group_Reference != null ?
                new ObjectParameter("Group_Reference", group_Reference) :
                new ObjectParameter("Group_Reference", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var mainParameter = main.HasValue ?
                new ObjectParameter("Main", main) :
                new ObjectParameter("Main", typeof(bool));
    
            var copy_ComponentsParameter = copy_Components.HasValue ?
                new ObjectParameter("Copy_Components", copy_Components) :
                new ObjectParameter("Copy_Components", typeof(bool));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            var explodeParameter = explode.HasValue ?
                new ObjectParameter("Explode", explode) :
                new ObjectParameter("Explode", typeof(bool));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("User_id", user_id) :
                new ObjectParameter("User_id", typeof(int));
    
            var order_QuantityParameter = order_Quantity.HasValue ?
                new ObjectParameter("Order_Quantity", order_Quantity) :
                new ObjectParameter("Order_Quantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQuote", quoteRefToCopyParameter, sequenceParameter, user_ReferenceParameter, group_ReferenceParameter, statusParameter, mainParameter, copy_ComponentsParameter, quantityParameter, explodeParameter, user_idParameter, order_QuantityParameter);
        }
    
        public virtual int CopyQWCentre(Nullable<int> quoteRefToCopy, Nullable<int> newQuoteRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQWCentre", quoteRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int CopyQWCentreToWOWCentre(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyQWCentreToWOWCentre", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopySubContract(Nullable<int> quoteRefToCopy, Nullable<int> newQuoteRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopySubContract", quoteRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int CopyWOMaterial(Nullable<int> wOrderRefToCopy, Nullable<int> newWOrderRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyWOMaterial", wOrderRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopyWOPart(Nullable<int> wOrderRefToCopy, Nullable<int> newWOrderRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyWOPart", wOrderRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopyWOrder(Nullable<int> wOrderRefToCopy, Nullable<int> sequence, string user_Reference, string status, Nullable<bool> main, Nullable<bool> copy_Components, Nullable<double> quantity, Nullable<double> quantity_To_Build, Nullable<bool> explode, Nullable<bool> doneLevelZero, Nullable<int> levelZeroRef, Nullable<int> user_id, Nullable<bool> locked)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var sequenceParameter = sequence.HasValue ?
                new ObjectParameter("Sequence", sequence) :
                new ObjectParameter("Sequence", typeof(int));
    
            var user_ReferenceParameter = user_Reference != null ?
                new ObjectParameter("User_Reference", user_Reference) :
                new ObjectParameter("User_Reference", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var mainParameter = main.HasValue ?
                new ObjectParameter("Main", main) :
                new ObjectParameter("Main", typeof(bool));
    
            var copy_ComponentsParameter = copy_Components.HasValue ?
                new ObjectParameter("Copy_Components", copy_Components) :
                new ObjectParameter("Copy_Components", typeof(bool));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            var quantity_To_BuildParameter = quantity_To_Build.HasValue ?
                new ObjectParameter("Quantity_To_Build", quantity_To_Build) :
                new ObjectParameter("Quantity_To_Build", typeof(double));
    
            var explodeParameter = explode.HasValue ?
                new ObjectParameter("Explode", explode) :
                new ObjectParameter("Explode", typeof(bool));
    
            var doneLevelZeroParameter = doneLevelZero.HasValue ?
                new ObjectParameter("DoneLevelZero", doneLevelZero) :
                new ObjectParameter("DoneLevelZero", typeof(bool));
    
            var levelZeroRefParameter = levelZeroRef.HasValue ?
                new ObjectParameter("LevelZeroRef", levelZeroRef) :
                new ObjectParameter("LevelZeroRef", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("User_id", user_id) :
                new ObjectParameter("User_id", typeof(int));
    
            var lockedParameter = locked.HasValue ?
                new ObjectParameter("Locked", locked) :
                new ObjectParameter("Locked", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyWOrder", wOrderRefToCopyParameter, sequenceParameter, user_ReferenceParameter, statusParameter, mainParameter, copy_ComponentsParameter, quantityParameter, quantity_To_BuildParameter, explodeParameter, doneLevelZeroParameter, levelZeroRefParameter, user_idParameter, lockedParameter);
        }
    
        public virtual int CopyWOSubContract(Nullable<int> wOrderRefToCopy, Nullable<int> newWOrderRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyWOSubContract", wOrderRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopyWOTool(Nullable<int> wOrderRefToCopy, Nullable<int> newWOrderRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyWOTool", wOrderRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int CopyWOWCentre(Nullable<int> wOrderRefToCopy, Nullable<int> newWOrderRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyWOWCentre", wOrderRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<string> GetCheckSum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCheckSum");
        }
    
        public virtual int GetNextId(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNextId", tableNameParameter);
        }
    
        public virtual int GetQComponents(Nullable<int> quote_RefID)
        {
            var quote_RefIDParameter = quote_RefID.HasValue ?
                new ObjectParameter("Quote_RefID", quote_RefID) :
                new ObjectParameter("Quote_RefID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetQComponents", quote_RefIDParameter);
        }
    
        public virtual int GetWOComponents(Nullable<int> wOrder_RefID)
        {
            var wOrder_RefIDParameter = wOrder_RefID.HasValue ?
                new ObjectParameter("WOrder_RefID", wOrder_RefID) :
                new ObjectParameter("WOrder_RefID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetWOComponents", wOrder_RefIDParameter);
        }
    
        public virtual ObjectResult<GetWOrderDetails_Result> GetWOrderDetails(string user_Reference)
        {
            var user_ReferenceParameter = user_Reference != null ?
                new ObjectParameter("User_Reference", user_Reference) :
                new ObjectParameter("User_Reference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWOrderDetails_Result>("GetWOrderDetails", user_ReferenceParameter);
        }
    
        public virtual int InsertQComponents(Nullable<int> quote_RefID)
        {
            var quote_RefIDParameter = quote_RefID.HasValue ?
                new ObjectParameter("Quote_RefID", quote_RefID) :
                new ObjectParameter("Quote_RefID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertQComponents", quote_RefIDParameter);
        }
    
        public virtual int InsertQMaterialItem(Nullable<int> materialRefToCopy, Nullable<int> parentRef, string destination)
        {
            var materialRefToCopyParameter = materialRefToCopy.HasValue ?
                new ObjectParameter("MaterialRefToCopy", materialRefToCopy) :
                new ObjectParameter("MaterialRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertQMaterialItem", materialRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertQPartItem(Nullable<int> partRefToCopy, Nullable<int> parentRef, string destination)
        {
            var partRefToCopyParameter = partRefToCopy.HasValue ?
                new ObjectParameter("PartRefToCopy", partRefToCopy) :
                new ObjectParameter("PartRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertQPartItem", partRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertQSubContractItem(Nullable<int> subContractRefToCopy, Nullable<int> parentRef, string destination)
        {
            var subContractRefToCopyParameter = subContractRefToCopy.HasValue ?
                new ObjectParameter("SubContractRefToCopy", subContractRefToCopy) :
                new ObjectParameter("SubContractRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertQSubContractItem", subContractRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertQToolItem(Nullable<int> toolRefToCopy, Nullable<int> parentRef, string destination)
        {
            var toolRefToCopyParameter = toolRefToCopy.HasValue ?
                new ObjectParameter("ToolRefToCopy", toolRefToCopy) :
                new ObjectParameter("ToolRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertQToolItem", toolRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertQWCentreItem(Nullable<int> nextWCentreOpNum, Nullable<int> nextWCentreSeq, Nullable<int> parentRef, Nullable<int> wCentreRefToCopy, string destination)
        {
            var nextWCentreOpNumParameter = nextWCentreOpNum.HasValue ?
                new ObjectParameter("NextWCentreOpNum", nextWCentreOpNum) :
                new ObjectParameter("NextWCentreOpNum", typeof(int));
    
            var nextWCentreSeqParameter = nextWCentreSeq.HasValue ?
                new ObjectParameter("NextWCentreSeq", nextWCentreSeq) :
                new ObjectParameter("NextWCentreSeq", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var wCentreRefToCopyParameter = wCentreRefToCopy.HasValue ?
                new ObjectParameter("WCentreRefToCopy", wCentreRefToCopy) :
                new ObjectParameter("WCentreRefToCopy", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertQWCentreItem", nextWCentreOpNumParameter, nextWCentreSeqParameter, parentRefParameter, wCentreRefToCopyParameter, destinationParameter);
        }
    
        public virtual int InsertWOComponents(Nullable<int> wOrder_RefID)
        {
            var wOrder_RefIDParameter = wOrder_RefID.HasValue ?
                new ObjectParameter("WOrder_RefID", wOrder_RefID) :
                new ObjectParameter("WOrder_RefID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertWOComponents", wOrder_RefIDParameter);
        }
    
        public virtual int InsertWOMaterialItem(Nullable<int> materialRefToCopy, Nullable<int> parentRef, string destination)
        {
            var materialRefToCopyParameter = materialRefToCopy.HasValue ?
                new ObjectParameter("MaterialRefToCopy", materialRefToCopy) :
                new ObjectParameter("MaterialRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertWOMaterialItem", materialRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertWOPartItem(Nullable<int> partRefToCopy, Nullable<int> parentRef, string destination)
        {
            var partRefToCopyParameter = partRefToCopy.HasValue ?
                new ObjectParameter("PartRefToCopy", partRefToCopy) :
                new ObjectParameter("PartRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertWOPartItem", partRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertWOSubContractItem(Nullable<int> subContractRefToCopy, Nullable<int> parentRef, string destination)
        {
            var subContractRefToCopyParameter = subContractRefToCopy.HasValue ?
                new ObjectParameter("SubContractRefToCopy", subContractRefToCopy) :
                new ObjectParameter("SubContractRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertWOSubContractItem", subContractRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertWOToolItem(Nullable<int> toolRefToCopy, Nullable<int> parentRef, string destination)
        {
            var toolRefToCopyParameter = toolRefToCopy.HasValue ?
                new ObjectParameter("ToolRefToCopy", toolRefToCopy) :
                new ObjectParameter("ToolRefToCopy", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertWOToolItem", toolRefToCopyParameter, parentRefParameter, destinationParameter);
        }
    
        public virtual int InsertWOWCentreItem(Nullable<int> nextWCentreOpNum, Nullable<int> nextWCentreSeq, Nullable<int> parentRef, Nullable<int> wCentreRefToCopy, string destination)
        {
            var nextWCentreOpNumParameter = nextWCentreOpNum.HasValue ?
                new ObjectParameter("NextWCentreOpNum", nextWCentreOpNum) :
                new ObjectParameter("NextWCentreOpNum", typeof(int));
    
            var nextWCentreSeqParameter = nextWCentreSeq.HasValue ?
                new ObjectParameter("NextWCentreSeq", nextWCentreSeq) :
                new ObjectParameter("NextWCentreSeq", typeof(int));
    
            var parentRefParameter = parentRef.HasValue ?
                new ObjectParameter("ParentRef", parentRef) :
                new ObjectParameter("ParentRef", typeof(int));
    
            var wCentreRefToCopyParameter = wCentreRefToCopy.HasValue ?
                new ObjectParameter("WCentreRefToCopy", wCentreRefToCopy) :
                new ObjectParameter("WCentreRefToCopy", typeof(int));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertWOWCentreItem", nextWCentreOpNumParameter, nextWCentreSeqParameter, parentRefParameter, wCentreRefToCopyParameter, destinationParameter);
        }
    
        public virtual int QToWOCopy(Nullable<int> quoteRefToCopy, string user_Reference, Nullable<bool> copy_Components, string custOrderNo, Nullable<System.DateTime> strDeliveryDate, Nullable<double> quantity, Nullable<int> user_id, string isConfirmed, string publicNotes, string privateNotes, Nullable<System.DateTime> theOrderDate)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var user_ReferenceParameter = user_Reference != null ?
                new ObjectParameter("User_Reference", user_Reference) :
                new ObjectParameter("User_Reference", typeof(string));
    
            var copy_ComponentsParameter = copy_Components.HasValue ?
                new ObjectParameter("Copy_Components", copy_Components) :
                new ObjectParameter("Copy_Components", typeof(bool));
    
            var custOrderNoParameter = custOrderNo != null ?
                new ObjectParameter("CustOrderNo", custOrderNo) :
                new ObjectParameter("CustOrderNo", typeof(string));
    
            var strDeliveryDateParameter = strDeliveryDate.HasValue ?
                new ObjectParameter("strDeliveryDate", strDeliveryDate) :
                new ObjectParameter("strDeliveryDate", typeof(System.DateTime));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("User_id", user_id) :
                new ObjectParameter("User_id", typeof(int));
    
            var isConfirmedParameter = isConfirmed != null ?
                new ObjectParameter("isConfirmed", isConfirmed) :
                new ObjectParameter("isConfirmed", typeof(string));
    
            var publicNotesParameter = publicNotes != null ?
                new ObjectParameter("PublicNotes", publicNotes) :
                new ObjectParameter("PublicNotes", typeof(string));
    
            var privateNotesParameter = privateNotes != null ?
                new ObjectParameter("PrivateNotes", privateNotes) :
                new ObjectParameter("PrivateNotes", typeof(string));
    
            var theOrderDateParameter = theOrderDate.HasValue ?
                new ObjectParameter("theOrderDate", theOrderDate) :
                new ObjectParameter("theOrderDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QToWOCopy", quoteRefToCopyParameter, user_ReferenceParameter, copy_ComponentsParameter, custOrderNoParameter, strDeliveryDateParameter, quantityParameter, user_idParameter, isConfirmedParameter, publicNotesParameter, privateNotesParameter, theOrderDateParameter);
        }
    
        public virtual int QToWOCopyMaterial(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QToWOCopyMaterial", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int QToWOCopyPart(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QToWOCopyPart", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int QToWOCopySubContract(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QToWOCopySubContract", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int QToWOCopyTool(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QToWOCopyTool", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int QToWOCopyWCentre(Nullable<int> quoteRefToCopy, Nullable<int> newWOrderRef)
        {
            var quoteRefToCopyParameter = quoteRefToCopy.HasValue ?
                new ObjectParameter("QuoteRefToCopy", quoteRefToCopy) :
                new ObjectParameter("QuoteRefToCopy", typeof(int));
    
            var newWOrderRefParameter = newWOrderRef.HasValue ?
                new ObjectParameter("NewWOrderRef", newWOrderRef) :
                new ObjectParameter("NewWOrderRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QToWOCopyWCentre", quoteRefToCopyParameter, newWOrderRefParameter);
        }
    
        public virtual int RecordDeviation(Nullable<int> worder_Ref, Nullable<System.DateTime> newEndDate)
        {
            var worder_RefParameter = worder_Ref.HasValue ?
                new ObjectParameter("Worder_Ref", worder_Ref) :
                new ObjectParameter("Worder_Ref", typeof(int));
    
            var newEndDateParameter = newEndDate.HasValue ?
                new ObjectParameter("newEndDate", newEndDate) :
                new ObjectParameter("newEndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RecordDeviation", worder_RefParameter, newEndDateParameter);
        }
    
        public virtual int SplitEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SplitEmployee");
        }
    
        public virtual int WOToQCopy(Nullable<int> wOrderRefToCopy, string user_Reference, Nullable<int> user_Id)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var user_ReferenceParameter = user_Reference != null ?
                new ObjectParameter("User_Reference", user_Reference) :
                new ObjectParameter("User_Reference", typeof(string));
    
            var user_IdParameter = user_Id.HasValue ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WOToQCopy", wOrderRefToCopyParameter, user_ReferenceParameter, user_IdParameter);
        }
    
        public virtual int WOToQCopyMaterial(Nullable<int> wOrderRefToCopy, Nullable<int> newQuoteRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WOToQCopyMaterial", wOrderRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int WOToQCopyPart(Nullable<int> wOrderRefToCopy, Nullable<int> newQuoteRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WOToQCopyPart", wOrderRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int WOToQCopySubContract(Nullable<int> wOrderRefToCopy, Nullable<int> newQuoteRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WOToQCopySubContract", wOrderRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int WOToQCopyTool(Nullable<int> wOrderRefToCopy, Nullable<int> newQuoteRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WOToQCopyTool", wOrderRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int WOToQCopyWCentre(Nullable<int> wOrderRefToCopy, Nullable<int> newQuoteRef)
        {
            var wOrderRefToCopyParameter = wOrderRefToCopy.HasValue ?
                new ObjectParameter("WOrderRefToCopy", wOrderRefToCopy) :
                new ObjectParameter("WOrderRefToCopy", typeof(int));
    
            var newQuoteRefParameter = newQuoteRef.HasValue ?
                new ObjectParameter("NewQuoteRef", newQuoteRef) :
                new ObjectParameter("NewQuoteRef", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WOToQCopyWCentre", wOrderRefToCopyParameter, newQuoteRefParameter);
        }
    
        public virtual int CreateRevisionRecord(string order_Type, string record_Type, Nullable<int> order_Reference, Nullable<int> item_Reference, Nullable<int> employee_Reference, string contact_Name, Nullable<System.DateTime> ack_Date, Nullable<System.DateTime> promise_Date, string comment, Nullable<int> revision, Nullable<System.DateTime> revision_Date, Nullable<bool> acknowledged, ObjectParameter success)
        {
            var order_TypeParameter = order_Type != null ?
                new ObjectParameter("Order_Type", order_Type) :
                new ObjectParameter("Order_Type", typeof(string));
    
            var record_TypeParameter = record_Type != null ?
                new ObjectParameter("Record_Type", record_Type) :
                new ObjectParameter("Record_Type", typeof(string));
    
            var order_ReferenceParameter = order_Reference.HasValue ?
                new ObjectParameter("Order_Reference", order_Reference) :
                new ObjectParameter("Order_Reference", typeof(int));
    
            var item_ReferenceParameter = item_Reference.HasValue ?
                new ObjectParameter("Item_Reference", item_Reference) :
                new ObjectParameter("Item_Reference", typeof(int));
    
            var employee_ReferenceParameter = employee_Reference.HasValue ?
                new ObjectParameter("Employee_Reference", employee_Reference) :
                new ObjectParameter("Employee_Reference", typeof(int));
    
            var contact_NameParameter = contact_Name != null ?
                new ObjectParameter("Contact_Name", contact_Name) :
                new ObjectParameter("Contact_Name", typeof(string));
    
            var ack_DateParameter = ack_Date.HasValue ?
                new ObjectParameter("Ack_Date", ack_Date) :
                new ObjectParameter("Ack_Date", typeof(System.DateTime));
    
            var promise_DateParameter = promise_Date.HasValue ?
                new ObjectParameter("Promise_Date", promise_Date) :
                new ObjectParameter("Promise_Date", typeof(System.DateTime));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var revisionParameter = revision.HasValue ?
                new ObjectParameter("Revision", revision) :
                new ObjectParameter("Revision", typeof(int));
    
            var revision_DateParameter = revision_Date.HasValue ?
                new ObjectParameter("Revision_Date", revision_Date) :
                new ObjectParameter("Revision_Date", typeof(System.DateTime));
    
            var acknowledgedParameter = acknowledged.HasValue ?
                new ObjectParameter("Acknowledged", acknowledged) :
                new ObjectParameter("Acknowledged", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateRevisionRecord", order_TypeParameter, record_TypeParameter, order_ReferenceParameter, item_ReferenceParameter, employee_ReferenceParameter, contact_NameParameter, ack_DateParameter, promise_DateParameter, commentParameter, revisionParameter, revision_DateParameter, acknowledgedParameter, success);
        }
    
        public virtual int fo_GetWOComponents(Nullable<int> wOrder_RefID)
        {
            var wOrder_RefIDParameter = wOrder_RefID.HasValue ?
                new ObjectParameter("WOrder_RefID", wOrder_RefID) :
                new ObjectParameter("WOrder_RefID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fo_GetWOComponents", wOrder_RefIDParameter);
        }
    
        public virtual int fo_InsertWOComponents(Nullable<int> wOrder_RefID)
        {
            var wOrder_RefIDParameter = wOrder_RefID.HasValue ?
                new ObjectParameter("WOrder_RefID", wOrder_RefID) :
                new ObjectParameter("WOrder_RefID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fo_InsertWOComponents", wOrder_RefIDParameter);
        }
    
        public virtual int JD_CreateSplitOp(Nullable<int> wOWCentreRefToCopy, ObjectParameter newWOWCentreRef, Nullable<int> wCentreRef, Nullable<double> qty, string opName, Nullable<int> setting_Time_ms, Nullable<int> run_Time_ms, Nullable<decimal> overlapPerc, Nullable<decimal> overlap)
        {
            var wOWCentreRefToCopyParameter = wOWCentreRefToCopy.HasValue ?
                new ObjectParameter("WOWCentreRefToCopy", wOWCentreRefToCopy) :
                new ObjectParameter("WOWCentreRefToCopy", typeof(int));
    
            var wCentreRefParameter = wCentreRef.HasValue ?
                new ObjectParameter("WCentreRef", wCentreRef) :
                new ObjectParameter("WCentreRef", typeof(int));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(double));
    
            var opNameParameter = opName != null ?
                new ObjectParameter("OpName", opName) :
                new ObjectParameter("OpName", typeof(string));
    
            var setting_Time_msParameter = setting_Time_ms.HasValue ?
                new ObjectParameter("Setting_Time_ms", setting_Time_ms) :
                new ObjectParameter("Setting_Time_ms", typeof(int));
    
            var run_Time_msParameter = run_Time_ms.HasValue ?
                new ObjectParameter("Run_Time_ms", run_Time_ms) :
                new ObjectParameter("Run_Time_ms", typeof(int));
    
            var overlapPercParameter = overlapPerc.HasValue ?
                new ObjectParameter("OverlapPerc", overlapPerc) :
                new ObjectParameter("OverlapPerc", typeof(decimal));
    
            var overlapParameter = overlap.HasValue ?
                new ObjectParameter("Overlap", overlap) :
                new ObjectParameter("Overlap", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JD_CreateSplitOp", wOWCentreRefToCopyParameter, newWOWCentreRef, wCentreRefParameter, qtyParameter, opNameParameter, setting_Time_msParameter, run_Time_msParameter, overlapPercParameter, overlapParameter);
        }
    
        public virtual int JD_DeleteJoinedOp(Nullable<int> wOWCentreRefToDelete)
        {
            var wOWCentreRefToDeleteParameter = wOWCentreRefToDelete.HasValue ?
                new ObjectParameter("WOWCentreRefToDelete", wOWCentreRefToDelete) :
                new ObjectParameter("WOWCentreRefToDelete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JD_DeleteJoinedOp", wOWCentreRefToDeleteParameter);
        }
    
        public virtual int JD_JoinedSplitOp(Nullable<int> wOWCentreRefJoined)
        {
            var wOWCentreRefJoinedParameter = wOWCentreRefJoined.HasValue ?
                new ObjectParameter("WOWCentreRefJoined", wOWCentreRefJoined) :
                new ObjectParameter("WOWCentreRefJoined", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JD_JoinedSplitOp", wOWCentreRefJoinedParameter);
        }
    
        public virtual int JD_OpWasSplit(Nullable<int> wOWCentreRefSplit)
        {
            var wOWCentreRefSplitParameter = wOWCentreRefSplit.HasValue ?
                new ObjectParameter("WOWCentreRefSplit", wOWCentreRefSplit) :
                new ObjectParameter("WOWCentreRefSplit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JD_OpWasSplit", wOWCentreRefSplitParameter);
        }
    
        public virtual ObjectResult<string> JD_UpdateOpTime(Nullable<int> wOWCentre_Reference, string timeType, Nullable<long> time_ms, ObjectParameter success)
        {
            var wOWCentre_ReferenceParameter = wOWCentre_Reference.HasValue ?
                new ObjectParameter("WOWCentre_Reference", wOWCentre_Reference) :
                new ObjectParameter("WOWCentre_Reference", typeof(int));
    
            var timeTypeParameter = timeType != null ?
                new ObjectParameter("TimeType", timeType) :
                new ObjectParameter("TimeType", typeof(string));
    
            var time_msParameter = time_ms.HasValue ?
                new ObjectParameter("Time_ms", time_ms) :
                new ObjectParameter("Time_ms", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("JD_UpdateOpTime", wOWCentre_ReferenceParameter, timeTypeParameter, time_msParameter, success);
        }
    
        public virtual int spPing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPing");
        }
    
        public virtual int spUpdateLicenceRecord(string licenceType, string licenceString, ObjectParameter success)
        {
            var licenceTypeParameter = licenceType != null ?
                new ObjectParameter("LicenceType", licenceType) :
                new ObjectParameter("LicenceType", typeof(string));
    
            var licenceStringParameter = licenceString != null ?
                new ObjectParameter("LicenceString", licenceString) :
                new ObjectParameter("LicenceString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateLicenceRecord", licenceTypeParameter, licenceStringParameter, success);
        }
    
        public virtual ObjectResult<spWriteSession_Result> spWriteSession(Nullable<int> inID, string login_ID, string pC_Name, string client_Version, ObjectParameter iD, ObjectParameter sUCCESS)
        {
            var inIDParameter = inID.HasValue ?
                new ObjectParameter("inID", inID) :
                new ObjectParameter("inID", typeof(int));
    
            var login_IDParameter = login_ID != null ?
                new ObjectParameter("Login_ID", login_ID) :
                new ObjectParameter("Login_ID", typeof(string));
    
            var pC_NameParameter = pC_Name != null ?
                new ObjectParameter("PC_Name", pC_Name) :
                new ObjectParameter("PC_Name", typeof(string));
    
            var client_VersionParameter = client_Version != null ?
                new ObjectParameter("Client_Version", client_Version) :
                new ObjectParameter("Client_Version", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spWriteSession_Result>("spWriteSession", inIDParameter, login_IDParameter, pC_NameParameter, client_VersionParameter, iD, sUCCESS);
        }
    
        public virtual ObjectResult<string> UpdateWOTotals(Nullable<int> wOrder_Reference, ObjectParameter success)
        {
            var wOrder_ReferenceParameter = wOrder_Reference.HasValue ?
                new ObjectParameter("WOrder_Reference", wOrder_Reference) :
                new ObjectParameter("WOrder_Reference", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UpdateWOTotals", wOrder_ReferenceParameter, success);
        }
    }
}
