
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class Tricorn_User_Roles
{

    public int User_Role_Record_ID { get; set; }

    public int User_Record_ID { get; set; }

    public int Role_Record_ID { get; set; }



    public virtual Tricorn_User_Roles Tricorn_User_Roles1 { get; set; }

    public virtual Tricorn_User_Roles Tricorn_User_Roles2 { get; set; }

}

}
