
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class TUDF
{

    public int UDF_Reference { get; set; }

    public string Table_Name { get; set; }

    public string Field_Name { get; set; }

    public string Label_Caption { get; set; }

    public string Field_Type { get; set; }

    public string Field_Choices { get; set; }

    public Nullable<bool> Active { get; set; }

    public string Zone { get; set; }

    public Nullable<int> ColIndex { get; set; }

    public Nullable<int> RowIndex { get; set; }

    public Nullable<bool> Divider { get; set; }

    public Nullable<int> TED_Table_Reference { get; set; }

    public Nullable<bool> HalfWidth { get; set; }

    public string Comments_Field_Name { get; set; }

    public Nullable<int> ControlUsesPC { get; set; }

    public Nullable<bool> ControlLeftAlignMiddle { get; set; }

}

}
