//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOOperPlan
    {
        public int WOOperPlan_Reference { get; set; }
        public int WOWCentre_Reference { get; set; }
        public int WCentre_Reference { get; set; }
        public double Quantity_Required { get; set; }
        public System.DateTime Start_DateTime { get; set; }
        public System.DateTime End_DateTime { get; set; }
        public System.DateTime WOOperPlan_DateTime { get; set; }
        public bool Operation_Already_Finished { get; set; }
    }
}
