//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOrder_Templates_View
    {
        public int WOrder_Reference { get; set; }
        public string Part_Number { get; set; }
        public string Part_Issue { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Contract_Number { get; set; }
        public string Drawing_Number { get; set; }
        public string Drawing_Issue { get; set; }
        public bool Locked { get; set; }
        public string Name { get; set; }
        public Nullable<int> Customer_Reference { get; set; }
        public string User_Reference { get; set; }
        public Nullable<int> Quote_Reference { get; set; }
        public bool Main { get; set; }
        public string Status { get; set; }
        public string Method_Description { get; set; }
        public byte[] Long_Description { get; set; }
        public string Nominal_Code { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public Nullable<decimal> Converted_Price { get; set; }
        public string Type_Of_Order { get; set; }
        public string Location { get; set; }
        public byte[] Notes { get; set; }
        public byte[] Public_Notes { get; set; }
        public Nullable<int> Part_Reference { get; set; }
        public Nullable<int> Originating_WOrder_Reference { get; set; }
        public Nullable<int> NumBrokenlinks { get; set; }
        public Nullable<int> NumFileAttachments { get; set; }
    }
}
