
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tricorn
{

using System;
    using System.Collections.Generic;
    
public partial class WORDER_SCHEDULE_VIEW
{

    public int WOrder_Reference { get; set; }

    public string Part_Number { get; set; }

    public string Part_Issue { get; set; }

    public Nullable<decimal> Price { get; set; }

    public string Description { get; set; }

    public string Contract_Number { get; set; }

    public string Drawing_Number { get; set; }

    public string Drawing_Issue { get; set; }

    public bool Locked { get; set; }

    public string Name { get; set; }

    public Nullable<int> Customer_Reference { get; set; }

    public string User_Reference { get; set; }

    public Nullable<int> Quote_Reference { get; set; }

    public Nullable<int> Sequence { get; set; }

    public Nullable<decimal> Assembly_Cost { get; set; }

    public Nullable<double> Quantity { get; set; }

    public bool Main { get; set; }

    public string Customer_Order_Number { get; set; }

    public string Customer_Order_Item { get; set; }

    public Nullable<System.DateTime> Customer_Order_Date { get; set; }

    public Nullable<double> Quantity_To_Build { get; set; }

    public Nullable<System.DateTime> Schedule_Date { get; set; }

    public Nullable<int> Using_Reference { get; set; }

    public Nullable<double> Expr1 { get; set; }

}

}
