//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_MA1
    {
        public int NO { get; set; }
        public string DESCR { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> Multi { get; set; }
        public int GRNO { get; set; }
        public Nullable<decimal> PRODHRS { get; set; }
        public Nullable<decimal> PALET { get; set; }
        public Nullable<System.DateTime> STARTZEIT { get; set; }
        public Nullable<decimal> LIEGEZEIT { get; set; }
        public Nullable<decimal> TERMNO { get; set; }
        public Nullable<decimal> TYP { get; set; }
        public string Name { get; set; }
        public Nullable<double> GCOST { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> WAITMODE { get; set; }
        public Nullable<decimal> Speedmode { get; set; }
        public Nullable<decimal> Speedfactor { get; set; }
    }
}
