//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPECentral.Data.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaugeType
    {
        public GaugeType()
        {
            this.Gauges = new HashSet<Gauge>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CalibrationMethodId { get; set; }
        public byte DefaultCalibrationPeriod { get; set; }
    
        public virtual CalibrationMethod CalibrationMethod { get; set; }
        public virtual ICollection<Gauge> Gauges { get; set; }
    }
}
