//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPECentral.Data.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.Documents = new HashSet<Document>();
            this.OperationTools = new HashSet<OperationTool>();
        }
    
        public int Id { get; set; }
        public int Sequence { get; set; }
        public string Method { get; set; }
        public byte[] Notes { get; set; }
        public Nullable<int> SetupTime { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public int PartVersionId { get; set; }
        public int MachineGroupId { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual MachineGroup MachineGroup { get; set; }
        public virtual PartVersion PartVersion { get; set; }
        public virtual ICollection<OperationTool> OperationTools { get; set; }
    }
}
