
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CPECentral.Data.EF5
{

using System;
    using System.Collections.Generic;
    
public partial class PartAlert
{

    public int Id { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    public string Description { get; set; }

    public int PartId { get; set; }



    public virtual Part Part { get; set; }

}

}
