//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPECentral.Data.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartVersion
    {
        public PartVersion()
        {
            this.Methods = new HashSet<Method>();
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string VersionNumber { get; set; }
        public int PartId { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<int> DrawingDocumentId { get; set; }
    
        public virtual ICollection<Method> Methods { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Part Part { get; set; }
    }
}
