//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPECentral.Data.EF5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolGroup
    {
        public ToolGroup()
        {
            this.Tools = new HashSet<Tool>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int ParentToolGroupId { get; set; }
    
        public virtual ICollection<Tool> Tools { get; set; }
    }
}
